### ISSUE TITLE
so ，where is the code ?

### ISSUE THREAD

**Issue by vicentowang** [TRI-ML/packnet-sfm#1]

**Comment by madebyollin** [comment]
(Not the author) there's an unofficial reimplementation here: https://github.com/FangGet/PackNet-SFM-PyTorch but they haven't matched the result quality yet.

**Comment by vguizilini** [comment]
Thank you for the interest in our work, we have finally released inference code for PackNet-SfM, I hope that's helpful!

**Comment by madebyollin** [comment]
@vguizilini Awesome! Thanks for releasing :)
