### ISSUE TITLE
KITTI_raw data missing

### ISSUE THREAD

**Issue by pursueyyh** [TRI-ML/packnet-sfm#100]
Hello. Thanks a lot for providing the implementation of the model.

I am trying to train the model with KITTI_raw datasets. However, the datasets downloaded from the link you offerd (https://tri-ml-public.s3.amazonaws.com/github/packnet-sfm/datasets/KITTI_raw.tar.gz) only have one file (/2011_09_30). It can not match the required data in eigen_zhou. Is the data missing in the download process?  Or  is the datasets from the link you offered uncompleted?

Thanks!

**Comment by VitorGuizilini-TRI** [comment]
I often download KITTI from that link for internal use, so I'm confident that the data itself is fine. 
Can you try downloading again? It should be 92.7GB.

**Comment by pursueyyh** [comment]
@VitorGuizilini-TRI Thanks for your reply.
The download file is 92.7GB. But the uncompressed file is only 6.05GB. Maybe something wrong in the downloading process or uncompressing process. I will try to download again. Thanks.

**Comment by pursueyyh** [comment]
When I use the command to download the KITTI_raw datasets(curl -s https://tri-ml-public.s3.amazonaws.com/github/packnet-sfm/datasets/KITTI_raw.tar | tar -xv -C /data/datasets/), there is something wrong:

......
KITTI_raw/2011_09_30/2011_09_30_drive_0018_sync/image_02/data/0000000538.png
KITTI_raw/2011_09_30/2011_09_30_drive_0018_sync/image_02/data/0000000159.png
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

Can you help me with this? What is the size of the uncompress datasets?

**Comment by VitorGuizilini-TRI** [comment]
Any luck with that? I have no issues downloading the dataset from my end here.

**Comment by pursueyyh** [comment]
@VitorGuizilini-TRI  Thanks for your reply. The dataset now is complete after I downloaded again. 
I guess it is caused by network problems during downloading. 
Thanks for your kindness!
