### ISSUE TITLE
how to obtain the qualitative trajectory on kitti

### ISSUE THREAD

**Issue by alter409** [TRI-ML/packnet-sfm#101]
hello, I used the code in issue 72 to evaluate kitti sequence 09, but the result is wrong, some results are as follows :

{"000001.png": {"pose": [0.9999678730964661, -0.000983253470622003, 0.007953513413667679, 9.94056352381176e-05, 0.0009826867608353496, 0.9999995231628418, 7.516442565247416e-05, -5.28673890339668e-06, -0.007953583262860775, -6.734619819326326e-05, 0.9999683499336243, 8.271909243553991e-05, 0, 0, 0, 1], "rot": [[0.9999678730964661, -0.000983253470622003, 0.007953513413667679], [0.0009826867608353496, 0.9999995231628418, 7.516442565247416e-05], [-0.007953583262860775, -6.734619819326326e-05, 0.9999683499336243]], "trans": [9.873933595372364e-05, -5.390048045228468e-06, 8.350670395884663e-05]}, "000002.png": {"pose": [0.9998927543913689, -0.004335879327946564, 0.013990273088394328, 0.00014249459638074035, 0.00431855365046911, 0.9999899509861953, 0.0012683908902226685, -1.7385068599254282e-05, -0.013995630497447693, -0.0012078370251868812, 0.9999013500054658, 0.0002622883515526121, 0, 0, 0, 1], "rot": [[0.9999762177467346, -0.003343456657603383, 0.006038271356374025], [0.003336346009746194, 0.9999938011169434, 0.0011872947216033936], [-0.006042202934622765, -0.0011671206448227167, 0.9999811053276062]], "trans": [4.051890573464334e-05, -1.2501925084507093e-05, 0.00018013901717495173]}, "000003.png": {"pose": [0.9998394364924791, -0.010459354895667908, 0.01454965960261503, 0.00016231816606781418, 0.010455010594869462, 0.9999453377413505, 0.00037464913673032174, -5.480610528248278e-05, -0.01455278164950886, -0.0002224722075198655, 0.9998940608838649, 0.0005047415283853803, 0, 0, 0, 1], "rot": [[0.9999809861183167, -0.006136802025139332, 0.000555568840354681], [0.006137298420071602, 0.9999807476997375, -0.0008961492567323148], [-0.0005500586703419685, 0.0008995418902486563, 0.9999994039535522]], "trans": [1.590078136359807e-05, -3.7680267269024625e-05, 0.00024270190624520183]}, "000004.png": {"pose": [0.9998550554238105, -0.01606778629322492, 0.005634011653252731, 0.00011392274143311418, 0.016082962526636192, 0.9998672471699298, -0.002658667343123723, -8.818018001421741e-05, -0.005590545176895343, 0.002748893103837889, 0.9999805802634728, 0.0006010910754390049, 0, 0, 0, 1], "rot": [[0.9999440312385559, -0.0056515890173614025, -0.008947188965976238], [0.005625486373901367, 0.9999799132347107, -0.0029399176128208637], [0.008963623084127903, 0.0028894206043332815, 0.9999556541442871]], "trans": [-4.946380795445293e-05, -3.2327174267265946e-05, 9.61637488217093e-05]}, "000005.png": {"pose": [0.9997636157861115, -0.020830479466942994, -0.006231675737400191, 5.245917580147099e-05, 0.02080418090495063, 0.9997746473584948, -0.0042557388424574304, -7.205157674485927e-05, 0.006318918168069096, 0.004125087262005678, 0.9999715406570157, 0.000797426347907154, 0, 0, 0, 1], "rot": [[0.9999179244041443, -0.004771185573190451, -0.011889602057635784], [0.004754797555506229, 0.9999877214431763, -0.0014062286354601383], [0.0118961650878191, 0.0013495805906131864, 0.99992835521698]], "trans": [-5.987286567687988e-05, 1.8215179807157256e-05, 0.00019664406136143953]}, 

then i used pose(1,4) as x, pose(3,4) as z, the plot trajectory map as follow:
![untitled](https://user-images.githubusercontent.com/19776631/101881478-75780100-3bcf-11eb-961d-7b001a41a5c7.jpg)
I want to know where the problem is, thank you!

**Comment by VitorGuizilini-TRI** [comment]
Hi, which pre-trained model did you use? I haven't thoroughly checked that PR, will do it as soon as possible.

**Comment by alter409** [comment]
> Hi, which pre-trained model did you use? I haven't thoroughly checked that PR, will do it as soon as possible.

hi, i used pre-trained model PackNet01_MR_semisup_CStoK

**Comment by VitorGuizilini-TRI** [comment]
Can you try a self-supervised model? The semi-supervision might compromise pose learning, since there are two conflicting losses/
