### ISSUE TITLE
Problem with using generated depth groundtruth

### ISSUE THREAD

**Issue by ChenHoy** [TRI-ML/packnet-sfm#102]
Hello,
I am using the ```dgp.datasets.synchronized_dataset``` methods to load the DDAD data. Since I am using image sequences, I use 
```
SynchronizedSceneDataset(
                path_to_json,
                split="train",
                datum_names=("CAMERA_01",),
                generate_depth_from_datum="lidar",
                forward_context=radius,
                backward_context=radius,
               )
```
to load my sequences. 

All of these work properly, however the depth maps are most of the time very sparse from lidar.  Often times there is only supervision data on the upper rows of the image (which would be the sky?).
When I see the results, that you achieve with PackNet, then I assume that you have better supervision available or train only self-supervised or with stereo supervision. 

Is the depth ground on the DDAD dataset really that sparse or am I doing somethings wrong when loading the datums? 

Thank you for you help!

Best regards,
Christian

**Comment by VitorGuizilini-TRI** [comment]
Are you using the DGPdataset provided in this repository or directly the SynchronizedSceneDataset? The DDAD depth maps are fairly dense, so there's probably an issue somewhere, and definitely there should not be supervision in the sky.

**Comment by ChenHoy** [comment]
Thanks for the quick response!

I used the loaders from the [dgp](https://github.com/TRI-ML/dgp) repo, i.e. this [file](https://github.com/TRI-ML/dgp/blob/master/dgp/datasets/synchronized_dataset.py). And the I downloaded the data with correct checksums from [DDAD](https://github.com/TRI-ML/DDAD). 

Yea, I thought so too. I will try your loader from this repo directly now. Would be nice if could sort this problem out ....

**Comment by RaresAmbrus** [comment]
Can you try using the DDAD [notebook](https://github.com/TRI-ML/DDAD/blob/master/notebooks/DDAD.ipynb) to visualize the data (images + depth)? There should definitely not be any supervision on the sky pixels ...

**Comment by ChenHoy** [comment]
Yeah, using the notebook I cant replicate the error I had before somehow. Everything looks fine there. 

I will investigate the rest of my Code before closing this.

**Comment by ChenHoy** [comment]
After carefully investigating the data, I came to the conclusion, that everything seems to work fine. Thank you for your help!

Would you say, that DDAD has sparser depth labels than KITTI and if so why? I noticed that supervised learning seems to be harder on this benchmark.

**Comment by VitorGuizilini-TRI** [comment]
DDAD has denser depth labels than KITTI (at least the raw LiDAR version, without accumulation). With DDAD we are evaluating depths of up to 200m, and the environment is more varied (different cities, more dynamic objects and such), which all contribute to create a more challenging benchmark. There are also multiple cameras, I'm not sure if you are using those as well.

**Comment by ChenHoy** [comment]
Ok I see, then I probably have another bug somewhere. I am only using the data from _Camera 0_ and a temporal sequence. Is it correct when I use 
```
for sequence in SynchronizedDataset(
                path/to/DDAD,
                split="train",
                datum_names=("CAMERA_01",),
                generate_depth_from_datum="lidar",
                forward_context=radius,
                backward_context=radius,):
  for frame in sequence:
    pose = frame["pose"].matrix
```
Will this be the correct pose of _Camera 0_ or just the lidar sensor and I would have to multiply this with ```frame["extrinsics"]```? I am having a hard time with my pose estimator ...

**Comment by VitorGuizilini-TRI** [comment]
The 'pose' key should give you camera pose in global coordinates, so no need for 'extrinsics' (that's to transform between sensors). One quick thing you can try: can you inverting frame['pose'] before using it? Maybe the transformation is the inverse of what you are looking for (i.e. camera to world instead of world to camera)
