### ISSUE TITLE
Why are original (and not augmented) images used to calculate the loss?

### ISSUE THREAD

**Issue by zshn25** [TRI-ML/packnet-sfm#103]
> https://github.com/TRI-ML/packnet-sfm/blob/2698f1fb27785275ef847f3dbbd550cf8fff1799/packnet_sfm/models/SelfSupModel.py#L89-L92

**Comment by VitorGuizilini-TRI** [comment]
We feed the augmented image to the depth network, for the photometric calculation we believe there is no need, since the calculation is appearance-based and augmentation could create artifacts that compromise matching in different viewpoints.

**Comment by zshn25** [comment]
But isn't SSIM invariant to the jitter augmentations?

**Comment by VitorGuizilini-TRI** [comment]
Sure, and in fact I don't think we observe any significant changes if we go one way or another (raw or augmented images). This is mostly a design choice, since we have access to the raw untouched image it is cleaner if we use them directly instead of the augmented one.

**Comment by zshn25** [comment]
Yes, makes sense to use it while you already have it. Thanks!
