### ISSUE TITLE
parameters of your depth network

### ISSUE THREAD

**Issue by ZhongkaiZhou** [TRI-ML/packnet-sfm#106]
Thank you for your excellent work! I want to compare your model with mine. So, i want to know how many parameters your depth network has?

**Comment by VitorGuizilini-TRI** [comment]
We have some numbers on the paper, the PackNet model as described has around 128M parameters, and there is also a slimmer version with 78M parameters.

**Comment by ZhongkaiZhou** [comment]
Thank you very much!
