### ISSUE TITLE
Training with Cropped Images?

### ISSUE THREAD

**Issue by jdriscoll319** [TRI-ML/packnet-sfm#109]
I have a dataset of images from a dashcam. Unfortunately, the car hood is still visible and takes up a large portion of the image. I suspect that this is having a negative impact on training. I'm curious if I generate a dummy NRS template and then crop it in the same manner I crop out the car hood from the images, will the network still be able to train successfully?

**Comment by VitorGuizilini-TRI** [comment]
We are currently doing some similar experiments and definitely the hood will have a negative impact on training. You should be able to crop the image and the NRS template normally, that will enable the network to train successfully.

**Comment by jdriscoll319** [comment]
Are there image shape restrictions related to this?
I'm resizing my images to 252x448 (16:9 resolution) then cropping out the bottom to a final image size of 192x448. However, when I do this the average loss reported during training is `nan`. 
If I resize to 224x384 (still 16:9, but I need to account for memory constraints in my current setup), and don't crop, I get an actual value reported again.
Any ideas?

**Comment by jdriscoll319** [comment]
Looks like the issue is with the way I'm generating my templates and not with anything in the NRS network/your codebase.

**Comment by VitorGuizilini-TRI** [comment]
Yeah, I don't think there are any shape restrictions. Some networks require images that are multiple of 16, so you need to resize to specific numbers, but that's it. I'm glad you found the issue, I'm closing this for now, feel free to reopen if something else comes up!

**Comment by porwalnaman01** [comment]
Hello there, I am also trying to train it on a different dataset containing just images in a folder. I am also using ImageDataset but when I try to run the script, it reads the validation files but do not read the training files. My dataset is a folder containing .jpg images. Can you please help me here? Thanks in advance!

Config file that I am using :

    model:
        name: 'SelfSupModel'
        optimizer:
            name: 'Adam'
            depth:
                lr: 0.0002
            pose:
                lr: 0.0002
        scheduler:
            name: 'StepLR'
            step_size: 30
            gamma: 0.5
        depth_net:
            name: 'DepthResNet'
            version: '18pt'
        pose_net:
            name: 'PoseResNet'
            version: '18pt'
        params:
            crop: 'garg'
            min_depth: 0.0
            max_depth: 80.0
    datasets:
        augmentation:
            image_shape: (192, 640)
        train:
            batch_size: 4
            dataset: ['Image']
            path: ['/disk1/dan/datasets/vgg-faces/train']
            split: ['train_split.txt']
    
        validation:
            dataset: ['Image']
            path: ['/disk1/dan/datasets/vgg-faces/val']
            split: ['val_split.txt']
        test:
            dataset: ['KITTI']
            path: ['/disk1/dan/datasets/KITTI_tiny']
            split: ['kitti_tiny.txt']
            depth_type: ['velodyne']
    
    checkpoint:
        filepath: '/disk1/dan/Naman/packnet-sfm-0.1.2/experiments1'
        monitor_index: 0
        mode: 'min'
