### ISSUE TITLE
Dummy NRS Template - Normalize the Surface?

### ISSUE THREAD

**Issue by jdriscoll319** [TRI-ML/packnet-sfm#110]
I have a custom dataset with images that I don't have the calibration parameters for. In the NRS paper, you describe a method for generating a "dummy" template. The process seems mostly straightforward but could you clarify what you mean when you say "normalizing its surface" in section 4.3.2?

**Comment by VitorGuizilini-TRI** [comment]
The ray surface vectors should be normalized, that's what it means.

**Comment by jdriscoll319** [comment]
That's what I suspected, thanks for confirming!
