### ISSUE TITLE
How much GPU memory needed to produce the reported performance?

### ISSUE THREAD

**Issue by ruili3** [TRI-ML/packnet-sfm#112]
Hi, thanks a lot for the work! I have a question for the GPU memory of PackNet-sfm. In the paper, the batch size is set to 4, totally 8 V100 GPU is used for parallel tranining. I wonder how much GPU resources is needed to run the settings reported in the paper? (Full model with 192x640 input size)?
 
And one more question, batch size ==4 means there are 4 image on every GPU and the total batch size is 32 (4x 8 GPU) ?

Thank you very much!

**Comment by VitorGuizilini-TRI** [comment]
Thank you for the interest in our work! Each GPU has 16 GB memory, and the network takes up a good percentage of that, so you will need 8 x 16 GB GPUs. Reducing the batch size to 2 shouldn't hurt the performance significantly, so you can probably get away with half of that and train longer. 

Yes, it's a batch size of 4 per GPU, so the total is 32.

**Comment by ruili3** [comment]
Got that, thank you a lot for the reply!

VitorGuizilini-TRI <notifications@github.com> 于2021年1月22日周五 上午2:30写道：
