### ISSUE TITLE
How to perform on multi-GPUS

### ISSUE THREAD

**Issue by hhhharold** [TRI-ML/packnet-sfm#113]
I have 2 GPUs on my PC and I just use the default config file - train_kitti.yaml to train the model. When the model is training, I found that only one GPU is working. Where can I set the number of GPUs or the index of GPUs?

**Comment by VitorGuizilini-TRI** [comment]
We use MPI with Horovod for multi-GPU training. If you run with docker (`docker-run-mpi`) it should work, otherwise you can check the Makefile to find the corresponding command that should be used. Let me know if it works!

**Comment by VitorGuizilini-TRI** [comment]
That should solve the issue, let me know if it works so I can close this thread!

**Comment by hhhharold** [comment]
It worked, thanks~
