### ISSUE TITLE
The model results provided by this project do not correspond to those in Table 3 of your paper

### ISSUE THREAD

**Issue by HHUZZK** [TRI-ML/packnet-sfm#114]
How can I find the model in table3 of your paper? PackNet-SfM M 640 x 192 K 0.111 0.785 4.601 0.189 0.878 0.960 0.982.
The models provided in this project appears to be inconsistent with what are described in your paper?
If convenient, can you provide the  results produced by the model above on eigen_test_files ? Thank you so much！

**Comment by VitorGuizilini-TRI** [comment]
It should be this model here: 

https://tri-ml-public.s3.amazonaws.com/github/packnet-sfm/models/PackNet01_MR_selfsup_K.ckpt

We retrained the models using this repository to ensure everything is in order, so numbers might vary slightly from the ones reported on the paper. From what I see the new numbers are slightly better :)

**Comment by HHUZZK** [comment]
Thank you so much :)
