### ISSUE TITLE
Training with Synthetic / Dense Depth Annotations

### ISSUE THREAD

**Issue by AlfieBrash** [TRI-ML/packnet-sfm#116]
Instead of using sparse velodyne depth data, is it possible to implement training using dense depth annotations? (Grayscale 16bit PNG files obtained from synthetic data). 
Are there pre-made alternative options for depth_type for the config files?
Thank you

**Comment by VitorGuizilini-TRI** [comment]
Which dataset class are you going to use? The `depth_type` key could be anything and depends on the dataset, on KITTI you can add another folder inside `proj_depth` with the name you want and just set `depth_type` to that. We have done this internally for VKITTI2, I'll look into adding support for that dataset here as well.

**Comment by AlfieBrash** [comment]
I am also working with vKITTI 2. I would use the raw png files (or jpg for loading?). Did you need to implement a grayscale-depth decoder in your internal work? Thank you very much for the help.

**Comment by VitorGuizilini-TRI** [comment]
Hi, sorry for the late reply. What do you mean by grayscale - depth decoder?  For VKITTI2 you can still use RGB images as output, and convert the PNG depth maps to metric depth for supervision, then everything else remains the same.
