### ISSUE TITLE
Supervised training

### ISSUE THREAD

**Issue by AlfieBrash** [TRI-ML/packnet-sfm#119]
I am familiar with the training using stereo pairs and/or video frames. However, which (if any) of the following training methods may be implemented using your network?
a) single image with paired depth data (conventional supervised)
b) stereo images with paired depth data 
c) video with paired depth data
d) stereo video with paired depth data

The depth data is not sparse, therefore is it possible to use that with the 'semi-supervised' training approach you have outlined? Thank you for your assistance.

**Comment by VitorGuizilini-TRI** [comment]
Sorry for the late reply. We currently do not support stereo training, however it should be easy to extend given the available training/inference pipeline. That's probably going to happen at some point in the future, but it's not a priority right now.  

We do support self-supervised, semi-supervised and supervised training, using either dense or sparse ground-truth depth maps. When data is sparse the invalid depth pixels are masked out and not used for training, is that what you are asking?

**Comment by AlfieBrash** [comment]
Thank you for taking the time to reply, your work is really great. I was mostly unsure of how the supervised training was trained, but it is more clear to me now. I have been using dense data successfully (dense because captured from a virtual environment).
