### ISSUE TITLE
How to use annoted depth maps for evaluation?

### ISSUE THREAD

**Issue by Rodger-Huang** [TRI-ML/packnet-sfm#126]
Hi, thanks for your great work.
I want to evaluate with the improved groundtruth depth maps.
I change the `depth_type` in the `eval_kitti.yaml` from `velodyne` to `groundtruth`.
https://github.com/TRI-ML/packnet-sfm/blob/c03e4bf929f202ff67819340135c53778d36047f/configs/eval_kitti.yaml#L20

I want to know if this is correct? Or should I make any other changes?
Do you evaluate on the full image or on the cropped image?

**Comment by VitorGuizilini-TRI** [comment]
Thank you for your interest in our work!
Yes, that's all you need. We evaluate the full image, unless you provide a crop to be used as mask (the standard one used for KITTI is 'garg').

**Comment by Rodger-Huang** [comment]
Thank you for your reply. 
So, if I want to evaluate the full image, should I set `crop: ''` instead of `crop: 'garg'` in the `eval_kitti.yaml`?
https://github.com/TRI-ML/packnet-sfm/blob/c03e4bf929f202ff67819340135c53778d36047f/configs/eval_kitti.yaml#L10

**Comment by VitorGuizilini-TRI** [comment]
Yes, then every valid ground-truth depth pixel will be evaluated.

**Comment by Rodger-Huang** [comment]
Thank you for your reply.
