### ISSUE TITLE
A question about 3D point projection

### ISSUE THREAD

**Issue by KruskalLin** [TRI-ML/packnet-sfm#127]
Thanks for your great work! I'm studying some of your geometry code but I met a question about the world point projection method.

In file `camera.py` the [projection](https://github.com/TRI-ML/packnet-sfm/blob/c03e4bf929f202ff67819340135c53778d36047f/packnet_sfm/geometry/camera.py#L172-L173) 
```python
"""
        Projects 3D points onto the image plane
        Parameters
        ----------
        X : torch.Tensor [B,3,H,W]
            3D points to be projected
        frame : 'w'
            Reference frame: 'c' for camera and 'w' for world
        Returns
        -------
        points : torch.Tensor [B,H,W,2]
            2D projected points that are within the image boundaries
        """
B, C, H, W = X.shape
assert C == 3

if frame == 'c':
    Xc = self.K.bmm(X.view(B, 3, -1))
elif frame == 'w':
    Xc = self.K.bmm((self.Tcw @ X).view(B, 3, -1))
else:
    raise ValueError('Unknown reference frame {}'.format(frame))
``` 
uses a batch of poses `self.Tcw` and a batch of world points `X`. But the size of `self.Tcw` is (B,4,4) and the size of `X` is (B,3,H,W). How these two can be dotted together?

**Comment by VitorGuizilini-TRI** [comment]
Sorry, somehow I missed this question and just noticed now that you closed the issue. Did you figure it out?
We have a custom @ operator for the pose class, that first rotates a 3D point using the R part of Tcw (3x3) and then translates it using the t part of Tcw (3x1), so the dimensionality works out.

https://github.com/TRI-ML/packnet-sfm/blob/c03e4bf929f202ff67819340135c53778d36047f/packnet_sfm/geometry/pose.py#L88

**Comment by KruskalLin** [comment]
Yeah, I saw it. Thanks for your reply!
