### ISSUE TITLE
How to calculate the pre-computed ground-truth depth maps?

### ISSUE THREAD

**Issue by Rodger-Huang** [TRI-ML/packnet-sfm#128]
Hi. 
Although you have provided the pre-computed ground-truth depth maps. But I want to know how you get the pre-computed ground-truth depth maps? The ground-truth depth maps seem not well consistent with the ground-truth used in monodepth2. Do you maybe know how the reason?

**Comment by VitorGuizilini-TRI** [comment]
We use the standard dev kit to produce the ground-truth KITTI depth maps, and have validated that these are the same as what other methods use by running their pre-trained models on our repository and getting the same numbers. 

One small inconsistency I have noticed with some other methods is that they transform the LiDAR pointcloud to the camera frame of reference, but still use the depth values from the LiDAR frame of reference to populate the depth map. I'm not sure if monodepth2 does that, but that's wrong, we should use the depth values from the camera frame of reference. In any case, the different is very small between these two versions of depth map, do you think that's what you are observing?

**Comment by Rodger-Huang** [comment]
Thank you for your reply. I think this is the reason for this phenomenon.
