### ISSUE TITLE
How much GPU memory for training NRS omnicam?

### ISSUE THREAD

**Issue by vbelissen** [TRI-ML/packnet-sfm#129]
Hi,

I've been trying to train the NRS model on omnicam data, however even with a NVIDIA V100 with 24GB of memory, I get a CUDA run out of memory issue.

Any advice on how to get this model training with less GPU memory?

Best

**Comment by VitorGuizilini-TRI** [comment]
We are currently looking into ways to decrease memory usage for NRS, but right now it indeed requires a lot of memory. You can try reducing image resolution, smaller batch sizes, or decreasing the patch size for the NRS warping. Let me know if any of these help!

**Comment by vbelissen** [comment]
Thank you very much! I have investigated the image resolution and it is indeed helpful. I'll look into the patch size now!
