### ISSUE TITLE
Unable to eval and test

### ISSUE THREAD

**Issue by GuCheng123** [TRI-ML/packnet-sfm#133]
I tried to use the file you provided  eigen_zhou_files , eigen_val_files ,eigen_test_files ，but why can't you test after training 1 EPOCH and the program breaks?
![微信图片_20210407180808](https://user-images.githubusercontent.com/37993189/113849730-5c254100-97cc-11eb-80ab-8e91d7d0721e.jpg)

**Comment by VitorGuizilini-TRI** [comment]
During training we do not test, only validate, so that's the dataset you need to set up (the validation dataset).  Testing happens after the model has been trained, and there are no epochs involved (it's a single evaluation of the test dataset).
