### ISSUE TITLE
Distributed training

### ISSUE THREAD

**Issue by DFLyan** [TRI-ML/packnet-sfm#134]
I want to train the network with several GPUs. I have seen the horovod module in the code, but it does not work. Whether I  need to set another parameter to achieve my aim? Or I need to write the distributing training code extra.

**Comment by VitorGuizilini-TRI** [comment]
The horovod distributed training should work, how are you running it?

**Comment by DFLyan** [comment]
> The horovod distributed training should work, how are you running it?

Thank you for your response. I have solved the problem. I haven't used the horovod module before, so I did not use "horovodrun -np 4 -H localhost:4" before "python train.py". And may I ask another problem here or open a new issue? I can not test model in DDAD_test dataset. 
![image](https://user-images.githubusercontent.com/27199157/116293855-dd6b6480-a7c9-11eb-8bb5-19f289a91c36.png)
 When I check the test dataset, I find the filename of  point_cloud in the *.json can not be found in the file. For example,  the filename in the 00000's json file is point_cloud/LIDAR/1568406550705785.npz, but  I can not find this file. Does this problem cause my testing failure?

**Comment by DFLyan** [comment]
> The horovod distributed training should work, how are you running it?

Thank you for your response. I have solved the problem. I haven't used the horovod module before, so I did not use "horovodrun -np 4 -H localhost:4" before "python train.py".
