### ISSUE TITLE
checkpoint can not be saved

### ISSUE THREAD

**Issue by DFLyan** [TRI-ML/packnet-sfm#139]
Hello, when I train the network, the model can not be saved. The error is shown as
![image](https://user-images.githubusercontent.com/27199157/118451211-95d05c80-b727-11eb-972a-ab69a18c92ec.png)
And when I want to find the reason why this error happens, I print the output of some variable in the file(model_checkpoint.py),
![image](https://user-images.githubusercontent.com/27199157/118452582-e1cfd100-b728-11eb-8ec6-6f0099d85b13.png)
then the outputs are 
![image](https://user-images.githubusercontent.com/27199157/118459777-a6380580-b72e-11eb-8473-e0e0a026c0e4.png)
Why the loss of val is 0? And does this cause the error? I have no idea to solve this problem, and I want to get help from you, thanks.

**Comment by surfii3z** [comment]
Not sure, but I think it tries to find determine which model to save by looking at the metric.

In my case, setting this config 
https://github.com/TRI-ML/packnet-sfm/blob/c03e4bf929f202ff67819340135c53778d36047f/configs/default_config.py#L23

to `save_top_k = -1` can bypass this problem as it will save all the models.

**Comment by VitorGuizilini-TRI** [comment]
Yes, you are trying to save based on a metric that doesn't exist, so setting `save_top_k = -1` will go around this issue.
