### ISSUE TITLE
Two stage training code to solve infinite depth

### ISSUE THREAD

**Issue by rvarun7777** [TRI-ML/packnet-sfm#14]
Hi,

First off, really good work :) Is there any plans of adding the two stage training technique code? Is it handled as a post processing step by creating point clouds using depth estimates and applying ransac to determine the ground plane?

**Comment by VitorGuizilini-TRI** [comment]
You are right, that's how it works. We are still working out some details before we can release the two-stage training technique code, but it won't be long!

**Comment by vbelissen** [comment]
> You are right, that's how it works. We are still working out some details before we can release the two-stage training technique code, but it won't be long!

Hi @VitorGuizilini-TRI, any update on this two-stage training?
