### ISSUE TITLE
3D convolution deployment?

### ISSUE THREAD

**Issue by jinfagang** [TRI-ML/packnet-sfm#140]
Is there a way to deploy the 3d convolution to tensorrt or other platform?

**Comment by surfii3z** [comment]
There is a tutorial [here](https://developer.nvidia.com/blog/estimating-depth-beyond-2d-using-custom-layers-on-tensorrt-and-onnx-models/) for converting packnet to tensorrt.

I also adapt this tutorial to make it work on ROS. Probably [this](https://github.com/surfii3z/packnet_sfm_ros/blob/master/ros/trt_packnet_node) and [this](https://github.com/surfii3z/packnet_sfm_ros/blob/master/src/trt_packnet/trt_packnet.py) might be useful for you.

**Comment by jinfagang** [comment]
@surfii3z thanks for this useful link. Does tensorrt supports convolution3d btw?

**Comment by VitorGuizilini-TRI** [comment]
There is a tutorial on the NVIDIA website using packnet, maybe that will help you: 
https://docs.nvidia.com/deeplearning/tensorrt/sample-support-guide/index.html
