### ISSUE TITLE
Quite slow for training

### ISSUE THREAD

**Issue by sunlibocs** [TRI-ML/packnet-sfm#141]
Training the packet will take 9 hours for one epoch by using the default setting. It will take ~20 days to train 50 epochs.

How much time did you spend training the model?

So sorry for my troubles.

**Comment by surfii3z** [comment]
FYI, I trained 1 epoch of this [config](https://github.com/TRI-ML/packnet-sfm/blob/c03e4bf929f202ff67819340135c53778d36047f/configs/train_kitti.yaml) except for the batch size is 8. It uses around 1 hour for an epoch on 4 of Tesla V100 GPU.

**Comment by VitorGuizilini-TRI** [comment]
It should take around 40 minutes for one epoch using 8 GPUs, so @surfii3z's comment sounds about right. What is your configuration, @sunlibocs?
