### ISSUE TITLE
CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by tiassap** [TRI-ML/packnet-sfm#143]
Sorry to ask again very trivial question.

Is it possible to train packnet using this configuration: Ubuntu 20.04LTS, NVIDIA Driver Version: 460.27.04 CUDA Version: 11.2, and GeForce RTX 3070 8 GB?

on the readme it is written that the minimum GPU requirement is 6GB.

After typing command `make docker-run COMMAND="python3 scripts/train.py configs/overfit_kitti.yaml"` I could initiate docker container, but after a while when training started I always get this error:

>RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

Thank you in advance!

**Comment by VitorGuizilini-TRI** [comment]
I don't think I tried with this exact configuration, but we have updated our dockerfile a few times since open-sourcing and it seems to work fine. Based on your error message I think you need to update the CUDNN library as well, maybe it's outdated for these new versions.

**Comment by tiassap** [comment]
I have updated the CUDNN library. And retried it. But still I got this error:

>   File "/usr/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

I wonder what is wrong here..
