### ISSUE TITLE
Conflicting Dependencies When Building Docker

### ISSUE THREAD

**Issue by j2innet** [TRI-ML/packnet-sfm#148]
Step 38/47 : RUN git clone https://github.com/TRI-ML/dgp.git     && cd dgp     && pip3 install -r requirements.txt
 ---> Running in 4307e6b93018

ERROR: Cannot install -r requirements.txt (line 2) and botocore==1.12.79 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested botocore==1.12.79
    awscli 1.16.192 depends on botocore==1.12.182

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

Is there any way to resolve this issue? The conflict is in another repo(dgp).. Please help

**Comment by aliasghar53** [comment]
Getting the same error. Any solutions?

**Comment by VitorGuizilini-TRI** [comment]
I'll look into that, but an easy solution would be to not install `requirements.txt` and instead add the relevant libraries to the dockerfile itself.

**Comment by YoungseokOh** [comment]
Check this : https://github.com/TRI-ML/dgp/issues/9
