### ISSUE TITLE
Failure cases

### ISSUE THREAD

**Issue by C-Anonymity** [TRI-ML/packnet-sfm#160]
![eigen_test_files_0000000019](https://user-images.githubusercontent.com/32475718/124474448-1da32080-ddd3-11eb-9799-aa8500a7a8a6.png)
![eigen_test_files_0000000021](https://user-images.githubusercontent.com/32475718/124474481-272c8880-ddd3-11eb-8bb6-93463efb780a.png)
I found that the PackNet-SfM cannot accurately estimate the depth of the man in white. The depth of his upper body is consistent with the background. What is the reason? Thanks in advance.

**Comment by VitorGuizilini-TRI** [comment]
Self-supervised learning methods have issues with dynamic objects, that's why you are seeing those artifacts. There are some techniques that can mitigate that, and we use a few (automasking, minimum reprojection error), however it does not completely eliminate this issue.

**Comment by C-Anonymity** [comment]
Thank you so much!
