### ISSUE TITLE
horovorun Multi gpu Error

### ISSUE THREAD

**Issue by sjg02122** [TRI-ML/packnet-sfm#165]
The model works well on my server

and  I try to run the model using multi-gpu (horovorun -np # ~~) 

Even though I never change anything, I face the problem GPU out of memory
(It was working well only single gpu)

How to can I fix this problem?

**Comment by VitorGuizilini-TRI** [comment]
Can you try using our provided dockerfile, so it's the same configuration?

**Comment by sjg02122** [comment]
I use the conda environments
Is it impossible on conda environments?

**Comment by VitorGuizilini-TRI** [comment]
I guess it is, if you set up all required packages inside the conda environment.
