### ISSUE TITLE
Can not build docker

### ISSUE THREAD

**Issue by MR-520DAI** [TRI-ML/packnet-sfm#169]
When I am building docker image，this commond is wrong！

Collecting git+https://github.com/horovod/horovod.git@65de4c961d1e5ad2828f2f6c4329072834f27661
  Cloning https://github.com/horovod/horovod.git (to revision 65de4c961d1e5ad2828f2f6c4329072834f27661) to /tmp/pip-req-build-ysb6ixn4
  Running command git clone -q https://github.com/horovod/horovod.git /tmp/pip-req-build-ysb6ixn4
  Running command git rev-parse -q --verify 'sha^65de4c961d1e5ad2828f2f6c4329072834f27661'
  Running command git fetch -q https://github.com/horovod/horovod.git 65de4c961d1e5ad2828f2f6c4329072834f27661
  Running command git checkout -q 65de4c961d1e5ad2828f2f6c4329072834f27661
  Running command git submodule update --init --recursive -q

**Comment by MR-520DAI** [comment]
Collecting git+https://github.com/horovod/horovod.git@65de4c961d1e5ad2828f2f6c4329072834f27661
  Cloning https://github.com/horovod/horovod.git (to revision 65de4c961d1e5ad2828f2f6c4329072834f27661) to /tmp/pip-req-build-6vnbqn8x
  Running command git clone -q https://github.com/horovod/horovod.git /tmp/pip-req-build-6vnbqn8x
  fatal: unable to access 'https://github.com/horovod/horovod.git/': Empty reply from server
WARNING: Discarding git+https://github.com/horovod/horovod.git@65de4c961d1e5ad2828f2f6c4329072834f27661. Command errored out with exit status 128: git clone -q https://github.com/horovod/horovod.git /tmp/pip-req-build-6vnbqn8x Check the logs for full command output.
ERROR: Command errored out with exit status 128: git clone -q https://github.com/horovod/horovod.git /tmp/pip-req-build-6vnbqn8x Check the logs for full command output.
The command '/bin/bash -cu ldconfig /usr/local/cuda/targets/x86_64-linux/lib/stubs &&     HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_GPU_BROADCAST=NCCL HOROVOD_WITH_PYTORCH=1     pip install --no-cache-dir git+https://github.com/horovod/horovod.git@${HOROVOD_VERSION} &&     ldconfig' returned a non-zero code: 1
Makefile:65: recipe for target 'docker-build' failed
make: *** [docker-build] Error 1

**Comment by stellarpower** [comment]
> fatal: unable to access 'https://github.com/horovod/horovod.git/': Empty reply from server
This presumably would imply you had some type of network error at the time you built(?)
Does it build as of today?
