### ISSUE TITLE
How to split the Cityscapes for pretraining?

### ISSUE THREAD

**Issue by UltronAI** [TRI-ML/packnet-sfm#17]
Is there a .txt file containing training files? just like eigen_zhou_files you provide in the readme. 

I'll appreciate it if you would like to share the dataset file for CS and its training files list. Thanks!

**Comment by VitorGuizilini-TRI** [comment]
I can look into that, will keep you informed!

**Comment by UltronAI** [comment]
@VitorGuizilini-TRI Thanks for quick reply!
And another question is how di d you preprocess the images from CS, as they have different aspect ratios from Kitti ’s images. Crop or simply resize?
I think it's helpful for fair comparison for future work in this line. Thanks!

**Comment by VitorGuizilini-TRI** [comment]
For that particular model we are resizing CS images to the same resolution used for KITTI images.

**Comment by Mrils** [comment]
By the way, the compression package you used in training CS datasets is the leftImg8bit_sequence_trainvaltest.zip ?

**Comment by MingYang-buaa** [comment]
@UltronAI @VitorGuizilini-TRI Have you got the split files for cityscapes datasets?

**Comment by VitorGuizilini-TRI** [comment]
We are using the standard 2975 training images with the corresponding 30 frame context for self-supervised depth learning.

**Comment by hemangchawla** [comment]
@VitorGuizilini-TRI just to be on the same page, could you please confirm if you use triplets for training cityscapes or is that a set of 30 images (rather 29 images with +/-14 context images)?
