### ISSUE TITLE
generating 3D scene from image sequence

### ISSUE THREAD

**Issue by iariav** [TRI-ML/packnet-sfm#170]
Hi,
thanks for the amazing work.
I was wondering if you have a script to generate a 3D reconstruction from an image sequence as you demonstrate in your video here - 
https://www.youtube.com/watch?v=b62iDkLgGSI    (from 0:55)

it would be very appreciated.
thanks

**Comment by ayushmankumar7** [comment]
This is a much-needed request as the 3D reconstruction really looked awesome!

**Comment by morsingher** [comment]
Hi @iariav and @ZeyingXuHuaWei,

I'm not involved in this specific project, but glad to help. Once you have the image and the depth map, you just need to back-project each pixel in 3D with the simple equation:

X = depth * inv(intrinsics) * pixel

This is for a single image. If you want to accumulate multiple depth maps along a video sequence, make sure all the 3D points refer to the same frame (e.g. the pose of the first image). You should have a look at this work: https://github.com/Brummi/MonoRec. They do a similar thing and provide code for 3D reconstruction as well.

Hope it helps!

**Comment by iariav** [comment]
Thanks @morsingher for your help, but I don't understand why the authors ignore this issue for so long.. 
would help a lot to see the script they used instead of trying to incorporate someone else's to work with this repo

**Comment by VitorGuizilini-TRI** [comment]
I apologize for the delay. I have just open-sourced our visualization tool, it's [here](https://github.com/TRI-ML/camviz).  I hope that helps!  We will add more functionalities over time to generate the videos and plots we use in our publications.
