### ISSUE TITLE
ERROR：Unknown class PackNetSlimEnc01

### ISSUE THREAD

**Issue by Cc-Hy** [TRI-ML/packnet-sfm#175]
I'm trying to do inference on a KITTI 3D detection image with command:
`scripts/infer.py --checkpoint ckpt/PackNetSAN01_HR_sup_K.ckpt --input ../data/kitti/training/image_2/000002.png --output output/000002.png`
with ckpt 'PackNetSAN, Supervised (densified GT), 352x1216, K'
And in line
`model_wrapper= ModelWrapper(config, load_datasets=False)` 
I got error
Unknown class PackNetSlimEnc01
![image](https://user-images.githubusercontent.com/82150240/131462642-9c7d5992-b54f-4b43-89f8-efa35b37022a.png)
Can you help me with it? Thank you.

**Comment by alphaxvzf** [comment]
This error only appears with https://tri-ml-public.s3.amazonaws.com/github/packnet-sfm/models/PackNet01_MR_selfsup_D.ckpt checkpoint. Probably, it cannot find the corresponding DenseNet. There is no problem with, for example, with https://tri-ml-public.s3.amazonaws.com/github/packnet-sfm/models/PackNet01_MR_semisup_CStoK.ckpt checkpoint .

**Comment by VitorGuizilini-TRI** [comment]
Hi, sorry for the delay in replying. The configuration file in that checkpoint uses an older name for the packnet-san model. If you replace it with the proper name "PackNetSAN01" it should work. I hope that helps!

**Comment by alphaxvzf** [comment]
Hello,
Thank you for your reply.
Actually, I fixed it. I only wanted to note that the old error still existed in the repository.
Best regards, Pavel Redkin.
> 
>> 
>>> 
>>>Hi, sorry for the delay in replying. The configuration file in that checkpoint uses an older name for the packnet-san model. If you replace it with the proper name "PackNetSAN01" it should work. I hope that helps!
>>>—
>>>You are receiving this because you commented.
>>>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>>>Triage notifications on the go with GitHub Mobile for  iOS or  Android .  
>> 
>> 
>>С уважением,
>>Павел Редькин
***@***.***
>>

**Comment by VitorGuizilini-TRI** [comment]
Thank you, I will push a fix for that soon!
