### ISSUE TITLE
velocityloss with Cityscape

### ISSUE THREAD

**Issue by big-chan** [TRI-ML/packnet-sfm#177]
Hi, I want to know the setting during the training term in Cityscape. 
Did you use the velocity loss in Cityscape? If you used the velocity loss, how can I apply the velocity loss to the Cityscape? Did you use the odometry data in the Cityscape to apply velocity loss?

Thank you!

**Comment by VitorGuizilini-TRI** [comment]
I don't think we used velocity loss for Cityscapes, when we pre-trained on that for KITTI it was purely self-supervised. If you have access to the odometry you can use the translation vector as weak supervision for the velocity loss. I hope that helps!
