### ISSUE TITLE
Semantically-Guided Representation Learning for Self-Supervised Monocular Depth

### ISSUE THREAD

**Issue by HaddedMohamed** [TRI-ML/packnet-sfm#178]
Hello,
Can you please upload the part of the code "Semantically-Guided Representation Learning for Self-Supervised Monocular Depth",
I'm testing this model in only images dataset and I will train semantic segmentation model on them, After link the semantic eatures to 3d model.

Thank you for your response.

**Comment by VitorGuizilini-TRI** [comment]
Hi, we are still working on releasing code for that paper, this repository is not suited for semantic tasks, and we are slowly building towards that.

**Comment by SimonHanYANG** [comment]
HI,

Did you release the code of "Semantically-Guided Representation Learning for Self-Supervised Monocular Depth"? I am interested in the details of this paper and want to see the source code.

Thanks for your response.
