### ISSUE TITLE
Each pixel value of the depth map is 0.01

### ISSUE THREAD

**Issue by mengjiaos** [TRI-ML/packnet-sfm#180]
When I use NRS to train on the omnicam dataset, when inferring, the each pixel's value of the depth map is 0.01, and a yellow depth map is displayed.
![000000000](https://user-images.githubusercontent.com/65722130/135021618-dd97e5b0-e2cc-4dc6-83c7-f2818c4105d9.png)

**Comment by VitorGuizilini-TRI** [comment]
Seems like your depth maps is not converging, can you please try a smaller learning rate?
