### ISSUE TITLE
ratios in SILog Loss

### ISSUE THREAD

**Issue by adizhol** [TRI-ML/packnet-sfm#181]
Hi, 
why were the ratios chosen like this?
Your paper "Geometric Unsupervised Domain Adaptation for Semantic Segmentation" doesn't mention anything about it.

https://github.com/TRI-ML/packnet-sfm/blob/6e3161f60e7161115813574557761edaffb1b6d1/packnet_sfm/losses/supervised_loss.py#L56

**Comment by VitorGuizilini-TRI** [comment]
Hi, those are the default parameters for most implementations of the SILog loss. We chose other loss weights using grid search, but never modified those from the default values. I hope that helps!

**Comment by adizhol** [comment]
also, you take the root of the si log diff

**Comment by wellneck** [comment]
Hope it's not too late, LOL, these ratios are from BTS
#
From Big to Small: Multi-Scale Local Planar Guidance for Monocular Depth Estimation:
"we can see that it is a sum of the variance and a weighted squared mean of the error in log space. Therefore, setting a higher λ enforces more focusing on minimizing the variance of the error, and we use λ = 0.85 in this work. Also,we observe that properly scaling the range of the loss function improves convergence and the final training result."
