### ISSUE TITLE
question about camera reconstruct and project function

### ISSUE THREAD

**Issue by livey** [TRI-ML/packnet-sfm#187]
At camera.reconstruct, it uses self.Twc @ Xc, and at camera.project, it uses self.Tcw @ X. However, Twc means from world to camera translation, and Tcw means from camera to world translation, should it be self.Tcw @Xc and self.Twc @ X respectively?

**Comment by VitorGuizilini-TRI** [comment]
Thank you for that, I'll double check. Since everything works fine, worst case scenario is that the names are swapped, so it's just a matter of renaming them.

**Comment by livey** [comment]
> 

Yes. It does not influence the results. But the pose prediction has a different meaning.

**Comment by akshay-ka** [comment]
> > 
> 
> Yes. It does not influence the results. But the pose prediction has a different meaning.

So, this should make it clear that the PoseNet output corresponds to a transformation from the "source image" to "target Image". 
(Target image = input image that is fed to the depth network)

@livey This is also what you mean with your comment "But the pose prediction has a different meaning." right ?
