### ISSUE TITLE
2 Stage Training , RANSAC method Question

### ISSUE THREAD

**Issue by sjg02122** [TRI-ML/packnet-sfm#189]
Thank you very much for your work. This is very helpful for my research.

I have a question about how to solve the infinite depth problem using RANSAC (2-stage training).

1. I wonder how much the performance improved when re-sampling was performed using RANSAC.

2. I understand that the method of re-sampling is as follows.

2-1) Point Clouds are created using Depth Estimation.
2-2) The ground plane of Point Clouds is estimated using RANSAC.
2-3) Compare each pixel of the estimated Ground Plane and Depth map to filter things with significantly different values.

I understand that this process is carried out by designating threshold
At this time, when the threshold point is 10, does it mean that the number of sensed pixels is 10?

**Comment by VitorGuizilini-TRI** [comment]
Hi, thank you for your interest in our work!  This threshold means that we are evaluating all pixels to find the ground-plane, and removing frames if there are more than `threshold` pixels below the extracted ground plane. Let me know if that helps!
