### ISSUE TITLE
Geometric Unsupervised Domain Adaptation for Semantic Segmentation

### ISSUE THREAD

**Issue by BenBausch** [TRI-ML/packnet-sfm#193]
Hello, 

I would like to use 'Geometric Unsupervised Domain Adaptation for Semantic Segmentation' as a baseline to compare my master thesis against. I could not find the code necessary for this in the repo, therefore I wanted to ask if the code has already been published ? 

Thank you very much in advance!

Best regards
Ben

**Comment by BenBausch** [comment]
Any information on this ?

**Comment by VitorGuizilini-TRI** [comment]
Hi, sorry for not replying sooner, did you get it to work? We describe the hyperparameters in the paper.
