### ISSUE TITLE
3D point cloud reconstruction

### ISSUE THREAD

**Issue by chapa17** [TRI-ML/packnet-sfm#195]
Hello everyone, 

I want to construct 3D point cloud for which I require 3D points. I am using `def reconstruct()` from `camera.py` file but I am getting a point cloud which has some different scale. The depth map looks quit good but the point cloud is really bad. I am not able to figure out whether it is the problem with my implementation or it is the same.

If anyone has tried reconstruction I would be happy to learn.

Thank you!

**Comment by VitorGuizilini-TRI** [comment]
If you are using a purely self-supervised model, there is no metric scale in the depth map. Is that what you mean when you say different scale, and that the pointcloud is really bad?

**Comment by chapa17** [comment]
I guess I have figured out the cause. It is the cloud pixels in the 3D cloud that are stretched out and not in proper position. Which seems to be a drawback of self-supervised methods anyways. 

Thank you for your help!

**Comment by chapa17** [comment]
I am sorry to reopen the issue again. The point cloud I have generated using reconstruct() method does not lie exactly on the ground plane. By ground plane I mean that when I visualize the point cloud in Blender, it does not lie above the grid. My understanding is that the point cloud lies on the ground plane grid. I have attached the snapshot of my point cloud and an example point cloud.  The values which are generated are not aligned.
 
Point cloud generated from packnet-sfm
<img width="599" alt="Screenshot from 2021-12-15 09-20-40" src="https://user-images.githubusercontent.com/74726040/146151325-4632c8bc-be16-4608-8918-671f6540752c.png">

Example point cloud
<img width="512" alt="Screenshot from 2021-12-15 09-28-30" src="https://user-images.githubusercontent.com/74726040/146151313-59fba215-2ca4-45aa-bd53-b92a46afbbf2.png">


Can you please let me know where I went wrong?
