### ISSUE TITLE
How to force the model to learn the depth in meters?

### ISSUE THREAD

**Issue by Mrils** [TRI-ML/packnet-sfm#20]
Hi!

Thanks for your great work! But i'm curious how to force the model to learn the depth in meters , as the DepthDecoder only predict the value in 0~1.  

In my mind, the PoseNet may predict the truth scale with with the velocity supervision. But the output of the DepthNet must be multiplied by a factor to restore to the correct scale. Is right?

**Comment by VitorGuizilini-TRI** [comment]
Our depth networks predict inverse depth, so all you have to do is invert the output. On packnet_sfm.utils.depth there is a inv2depth function, you can use it to do that.

**Comment by Mrils** [comment]
Right, I got it. THX
