### ISSUE TITLE
About dgp : get_datum_index_for_datum_name

### ISSUE THREAD

**Issue by LionRoarRoar** [TRI-ML/packnet-sfm#207]
Hi,  thanks for your great work. I followed https://github.com/TRI-ML/dgp/blob/master/docs/VIRTUAL_ENV.md to build a dgp enviroment. But when I run the the generate_depth_map function, some errors happen: 

https://github.com/TRI-ML/packnet-sfm/blob/f59b1d615777a9987285a10e45b5d87b0369fa7d/packnet_sfm/datasets/dgp_dataset.py#L150

it notice "get_datum_index_for_datum_name" cannot be found. So I guess the dgp version I install is not compatible with your code. Could you please provide the used dgp version of your code?  Or, Do you have any description about this dgp library so I can replace or reproduce this fuction? 

Thanks!

**Comment by VitorGuizilini-TRI** [comment]
Can you try this DGP checkout: ` 9617e65ad351558636de5586a48db848eab578c6`?

**Comment by LionRoarRoar** [comment]
> Can you try this DGP checkout: ` 9617e65ad351558636de5586a48db848eab578c6`?

Thanks for your reply! It works.

**Comment by LionRoarRoar** [comment]
@VitorGuizilini-TRI  Sorry to bother you again, this checkout have the "get_datum_index_for_datum_name" function I metioned above, but it cannot be correctly installed.  Some error happens when I run "pip install --editable . "

ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by robin-karlsson0** [comment]
@VitorGuizilini-TRI @LionRoarRoar
Hi guys. Just letting you know that I'm experiencing the same problem. Cannot launch the training or eval processes for `train_packnet_san_ddad.yaml`. Could not get the old `dgp` commit to work either.

Hoping that the `packnet-sfm`'s interface to `dgp` can get an update? (Or perhaps it is easier to just modify the KITTI dataloader to work on DDAD?)

**Comment by robin-karlsson0** [comment]
Referring to #192, I managed to run `train_packnet_san_ddad.yaml` by
1. Installing the latest `dgp` version
2. Revert to the old commit
3. Copy the file `dgp/utils/pose.py` from the latest master into the old commit. 

Can confirm that training runs with a `Avg.loss` decreasing. Validation runs as well. Hoping this hacky setup will not affect the quality of the results :sweat_smile:

**Comment by AIGC-newbee** [comment]
> Referring to #192, I managed to run `train_packnet_san_ddad.yaml` by
> 
> 1. Installing the latest `dgp` version
> 2. Revert to the old commit
> 3. Copy the file `dgp/utils/pose.py` from the latest master into the old commit.
> 
> Can confirm that training runs with a `Avg.loss` decreasing. Validation runs as well. Hoping this hacky setup will not affect the quality of the results 😅

@robin-karlsson0 Thank you, your reply really helped me XD.!!!
If you met the same issue, do following steps:

1. cd /workspace/dpg
2. cp dpg/uitls/pose.py /workspace
3. git checkout -b 9617e65ad351558636de5586a48db848eab578c6
4. cp /workspace/pose.py dgp/utils
Done!
