### ISSUE TITLE
Working directory mismatch in Docker environment

### ISSUE THREAD

**Issue by tamamachi** [TRI-ML/packnet-sfm#21]
Hi,
In commit f41342d716a72e195a0e72cf12c6b563d182bb91, when you run`make doker-run` and other Docker-related targets,
the default working directory is set to `/workspace/packnet-sfm/`
but everything (code, data, confs...) is prepared under `/workspace/packnet/` .

This leads `python3 scripts/train.py checkpoint.ckpt` to fail because train.py is at `../packnet/scripts/train.py`.

**Comment by VitorGuizilini-TRI** [comment]
Thank you for pointing that out, I have pushed a quick fix and it should work now.

**Comment by tamamachi** [comment]
LGTM! Thank you for quick reply.
