### ISSUE TITLE
Custom data set training

### ISSUE THREAD

**Issue by luda1013** [TRI-ML/packnet-sfm#223]
Hallo, finaly i can get to this point where i can train with kitty tiny dataset and save the model.
But once i want to train my own dataset, i have this error saying that ZeroDivisionError: division by zero

Btw i dont use the docker, had no success with it. So i installed on computer

The dataset that i use in config yaml is dataset: ['Image']

Thank you very much for your help!

**Comment by ArminBaz** [comment]
Hey have you figured out this issue? If not you might need to employ the same solution done in this [issue](https://github.com/TRI-ML/packnet-sfm/issues/96#issuecomment-762436108).

**Comment by luda1013** [comment]
> Hey have you figured out this issue? If not you might need to employ the same solution done in this [issue](https://github.com/TRI-ML/packnet-sfm/issues/96#issuecomment-762436108).

Hallo ArminBaz,
thanks for replying, yeah i already figured it out. with the split like mentioned in that issue.
But i must tweak some lines in the packnet_sfm\datasets\image_dataset.py
