### ISSUE TITLE
About Figure 1 in FSM paper

### ISSUE THREAD

**Issue by LionRoarRoar** [TRI-ML/packnet-sfm#229]
Hi, thank you for your work. I'm interested in Figure 1 in the FSM paper. I wonder how you get the point cloud visualization in Figure 1? Is it ROS or other visualization tools? Is there any available visualization code at present？

**Comment by VitorGuizilini-TRI** [comment]
We have open-sourced our visualization tool here: https://github.com/tri-ml/camviz
I hope that helps!
