### ISSUE TITLE
Conversion inverse depth map to real distance for custom images?

### ISSUE THREAD

**Issue by trnmentoring** [TRI-ML/packnet-sfm#23]
If i want to get real distance per pixel for custom image, should i apply inv2depth function to infer.py output (depth from model_wrapper.depth)? Cause as for now, predicted distanced are pretty different from the real ones.

**Comment by VitorGuizilini-TRI** [comment]
Yes, the output of our depth networks is actually inverse depth, so you need to apply inv2depth. Also, if you are using a self-supervised model the output will not be metrically accurate, so you need to scale it first.

**Comment by trnmentoring** [comment]
Exactly, thanks for so fast reply. Do you have a script for scaling in your repo?

**Comment by VitorGuizilini-TRI** [comment]
I don't think we have it as a standalone function, but you can see how it's done here:

https://github.com/TRI-ML/packnet-sfm/blob/f44a19663159b521a2f7209c12c40cfe3ead7bd9/packnet_sfm/utils/depth.py#L248

**Comment by trnmentoring** [comment]
Ah, i see. thank you for your patience!
