### ISSUE TITLE
How to calculate our own ray surface template?

### ISSUE THREAD

**Issue by 942411526** [TRI-ML/packnet-sfm#249]

**Comment by 942411526** [comment]
we want to calculate the ray surface template from our dataset.

**Comment by VitorGuizilini-TRI** [comment]
Do you have a camera model you want to use as the template, or are you creating your own from scratch?

**Comment by 942411526** [comment]
> Do you have a camera model you want to use as the template, or are you creating your own from scratch?

we have some data on unknown camera parameters(such as other datasets and video from YouTube ) and some data captured by our camera realsense D435i

**Comment by VitorGuizilini-TRI** [comment]
A ray surface template is a HxWx3 tensor with viewing rays for each pixel on your image, so if you have any sort of camera model you can create it by unprojecting points to 3D space following that model, and normalizing them to unit length. After that, our network learns an offset that goes from that template to the "true" camera model.

**Comment by 942411526** [comment]
> A ray surface template is a HxWx3 tensor with viewing rays for each pixel on your image, so if you have any sort of camera model you can create it by unprojecting points to 3D space following that model, and normalizing them to unit length. After that, our network learns an offset that goes from that template to the "true" camera model.

Thanks for your response very much. I will do that.

**Comment by VitorGuizilini-TRI** [comment]
Great, let me know if it works, I'm closing this for now
