### ISSUE TITLE
Training with ImageDataset?

### ISSUE THREAD

**Issue by tamamachi** [TRI-ML/packnet-sfm#25]
Hi,
I'm trying to train this model with my private video data, but the program fails to save checkpoint file.
I'm afraid that something is wrong in ImageDataset or my conf for the dataset. 
Could you give me some advice?

Console outputs are like following:

```
Epoch 0 | Avg.Loss 0.0722: 100%|?????????????????????????????????????????????????| 856/856 [09:35<00:00,  1.49 images/s]
session1-frame_{:05d}-: 100%|?????????????????????????????????????????????????????| 746/746 [04:08<00:00, 3.00 images/s]
Traceback (most recent call last):
  File "scripts/train.py", line 62, in <module>
    train(args.file)
  File "scripts/train.py", line 57, in train
    trainer.fit(model_wrapper)
  File "/workspace/packnet-sfm/packnet_sfm/trainers/horovod_trainer.py", line 61, in fit
    self.check_and_save(module, validation_output)
  File "/workspace/packnet-sfm/packnet_sfm/trainers/base_trainer.py", line 42, in check_and_save
    self.checkpoint.check_and_save(module, output)
  File "/workspace/packnet-sfm/packnet_sfm/models/model_checkpoint.py", line 128, in check_and_save
    filepath = self.format_checkpoint_name(epoch, metrics)
  File "/workspace/packnet-sfm/packnet_sfm/models/model_checkpoint.py", line 117, in format_checkpoint_name
    filename = filename.format(**metrics)
ValueError: unexpected '{' in field name
```

My config for dataset is like following:

```
datasets:
    ...
    train:
        batch_size: 2
        dataset: ['Image']
        path: ['/workspace/packnet-sfm/data/my_video_001/session0']
        split: ["frame_{:05d}"]
        repeat: [1]
```

I have a number of images for training data and the path is like:
`/workspace/packnet-sfm/data/my_video_001/session0/frame_00123.png`

I looked into the code and found that ModelCheckpoint's `filename` had the value of:
`epoch={epoch:02d}_session1-frame_0000{={session1-frame_0000{:01d}--loss:.3f}`. 
This was the direct cause of the error above.

Thanks in advance,

**Comment by VitorGuizilini-TRI** [comment]
Hmm, that makes sense. When saving the checkpoint we use a string generated from the split name, and in the case of ImageDataset the split name contains "{}", which messes up the formatting.  I won't have time to fix it now, but you can go to this function and remove the part where we use the split, the error should go away:

https://github.com/TRI-ML/packnet-sfm/blob/f44a19663159b521a2f7209c12c40cfe3ead7bd9/packnet_sfm/utils/logging.py#L33

Thank you for catching that!

**Comment by tamamachi** [comment]
Removed reference to split name in `prepare_dataset_prefix`, then the error disappeared.
Thanks a lot!

**Comment by TPEmist** [comment]
Hi, @tamamachi can you possibily share your whole config file for this image set deploying, I'm trying to use my image dataset but keep getting errors. Thanks very much

**Comment by tamamachi** [comment]
@TPEmist Here's my config:

```yaml
arch:
    max_epochs: 10
model:
    checkpoint_path: "/workspace/packnet-sfm/data/PackNet01_MR_selfsup_D.ckpt"
    name: 'SelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0001
        pose:
            lr: 0.0001
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'PackNet01'
        version: '1A'
    pose_net:
        name: 'PoseNet'
        version: ''
    params:
        crop: ''
        min_depth: 0.0
        max_depth: 200.0
checkpoint:
        filepath: "/workspace/packnet-sfm/ckpt"
        save_top_k: -1
datasets:
    augmentation:
        image_shape: (384, 640)
    train:
        batch_size: 2
        dataset: ['Image']
        path: ['/workspace/packnet-sfm/data/my_video_001/session0']
        split: ["frame_{:05d}"]
        repeat: [10]
    validation:
        dataset: ['Image']
        path: ['/workspace/packnet-sfm/data/my_video_001/session1']
        split: ["frame_{:05d}"]
```

FYI, my `prepare_dataset_prefix` ls like:

```py3
def prepare_dataset_prefix(config, n):
    return '{}-{}'.format(
        os.path.splitext(config.path[n].split('/')[-1])[0],
        config.depth_type[n],
    )
```

Hope that helps,

**Comment by TPEmist** [comment]
@tamamachi Thanks for your reply! so did you trained successfully with pure image data set?

**Comment by AIGC-newbee** [comment]
> @TPEmist Here's my config:
> 
> ```yaml
> arch:
>     max_epochs: 10
> model:
>     checkpoint_path: "/workspace/packnet-sfm/data/PackNet01_MR_selfsup_D.ckpt"
>     name: 'SelfSupModel'
>     optimizer:
>         name: 'Adam'
>         depth:
>             lr: 0.0001
>         pose:
>             lr: 0.0001
>     scheduler:
>         name: 'StepLR'
>         step_size: 30
>         gamma: 0.5
>     depth_net:
>         name: 'PackNet01'
>         version: '1A'
>     pose_net:
>         name: 'PoseNet'
>         version: ''
>     params:
>         crop: ''
>         min_depth: 0.0
>         max_depth: 200.0
> checkpoint:
>         filepath: "/workspace/packnet-sfm/ckpt"
>         save_top_k: -1
> datasets:
>     augmentation:
>         image_shape: (384, 640)
>     train:
>         batch_size: 2
>         dataset: ['Image']
>         path: ['/workspace/packnet-sfm/data/my_video_001/session0']
>         split: ["frame_{:05d}"]
>         repeat: [10]
>     validation:
>         dataset: ['Image']
>         path: ['/workspace/packnet-sfm/data/my_video_001/session1']
>         split: ["frame_{:05d}"]
> ```
> 
> FYI, my `prepare_dataset_prefix` ls like:
> 
> ```python
> def prepare_dataset_prefix(config, n):
>     return '{}-{}'.format(
>         os.path.splitext(config.path[n].split('/')[-1])[0],
>         config.depth_type[n],
>     )
> ```
> 
> Hope that helps,

Thanks for your sharing. It's really help!
