### ISSUE TITLE
Reconstruction loss experiment

### ISSUE THREAD

**Issue by ffabi** [TRI-ML/packnet-sfm#26]
Hello, thanks for the great work!

In your paper, in figure 4, we can see a comparison of the input image, the reconstruction of the classical conv+maxpool+bilinear upsampling, and the reconstruction of the packnet architecture.

Can you provide code for this experiment?

**Comment by VitorGuizilini-TRI** [comment]
That's a great suggestion, I will add that to one of our next releases. Thanks!

**Comment by ffabi** [comment]
Thank you, keep up the great work! :)
