### ISSUE TITLE
using pre-trained semantic segmentation

### ISSUE THREAD

**Issue by iariav** [TRI-ML/packnet-sfm#28]
Hi,
First of all thank you for releasing this awesome repository and for your continuous support.
You mention in your readme that "can also use a fixed pre-trained semantic segmentation network to guide the representation learning further" but i didn't see any reference to it in the code.

Do you plan to include this feature in any of your upcoming releases?
thanks

**Comment by VitorGuizilini-TRI** [comment]
Thank you for the interest in our work! You are right, we currently don't support that particular network (it's based on our ICLR 2020 paper, found [here](https://arxiv.org/abs/2002.12319)). However, we are working on that and will release our semantically-guided depth network soon.

**Comment by chapa17** [comment]
@VitorGuizilini-TRI Thank you very much for sharing such a great work. I also saw you results when included with semantic depth networks. I am curious to visualize the results on my own dataset. 

May I know when are you planning to release the semantically-guided depth network soon or would it take a while?

Thanks again :)

**Comment by SBaokun** [comment]
I am also looking forward to kown  when will you release your semantically-guided depth network ???
thanks!!!!
