### ISSUE TITLE
Which GPU is used? ("Titan V100 GPU")

### ISSUE THREAD

**Issue by cgebbe** [TRI-ML/packnet-sfm#29]
Thanks for your contribution first of all.

The paper states "an inference time of 60ms on a **Titan V100 GPU**". If I'm not mistaken, such a GPU does not exist. It is either the "Titan V" or the "Tesla V100".  Could you clarify please?

**Comment by VitorGuizilini-TRI** [comment]
Thank you for catching that typo, use use a Tesla V100.
