### ISSUE TITLE
Inference on video

### ISSUE THREAD

**Issue by Pari-singh** [TRI-ML/packnet-sfm#35]
Hi @VitorGuizilini,

Thanks for your code and the great work! I am trying to get the inference on a custom video/image-sequence, and so was wondering if there needs a major change in the config or is to be done frame-by-frame in the video?

Thanks in advance

**Comment by VitorGuizilini-TRI** [comment]
Thank you! 

Right now the only way is splitting your video frame-by-frame, running inference on the folder and then combining the predicted depth maps back. However, adding support to direct video processing doesn't sound too hard and would be useful, I will look into that. In the end it will still be frame-by-frame, but doing the splitting/combining in the code itself.
