### ISSUE TITLE
About ADE20k datasets

### ISSUE THREAD

**Issue by WHUWBS** [TRI-ML/packnet-sfm#38]
Hi @VitorGuizilini,

Thanks for your code and the great work! 
I am trying to train your model on ADE20k(MIT) datasets which have no depth information and parameters like camera intrinsics. In your paper ,you trained your model on cityscapes whose situation is similar to ADE20k, could you tell me how to train datasets like ADE20k and cityscapes?
Thank you very much!!

**Comment by VitorGuizilini-TRI** [comment]
Thanks! When no intrinsics are available we can approximate by setting fx = cx = w/2 and fy = cy = h / 2. 
This should be enough to produce reasonable projected depth maps, but if you are looking for accurate pointclouds it probably won't work, the real intrinsics are needed in that case.
Let me know how it goes, this dataset looks very interesting!

**Comment by WHUWBS** [comment]
Thanks for reply! I will try as you have mentioned above. If have any result , I will show you here.

**Comment by porwalnaman01** [comment]
Hi @WHUWBS did you find any way to predict intrinsics for each image of your dataset while training?
