### ISSUE TITLE
Possible to replace PoseNet by the groudtruth pose extracted from IMU

### ISSUE THREAD

**Issue by flamehaze1115** [TRI-ML/packnet-sfm#39]
Thanks for such excellent work! I notice that you extract camera pose from IMU and just use translation in velocity loss. Is it possible to replace the PoseNet by the camera pose from IMU?

**Comment by ymaocdc** [comment]
I have the same question as @flamehaze1115 
The question is more likely to be how PoseNet influence the final results. If we use the GT pose during training, will we get better depth prediction? I have not read from any paper to my knowledge about the ablation study on this part. If anyone can point out where I should look at, that will be great.

**Comment by VitorGuizilini-TRI** [comment]
@flamehaze1115 It is definitely possible (replace PoseNet with GT pose), we have experimented with it in the past. Interestingly, we did not see significant improvement when using GT pose compared to learned pose, but as @ymaocdc said, I don't think there have been many papers with such ablation study.
