### ISSUE TITLE
error on the step 5: bash evaluate_kitti.sh

### ISSUE THREAD

**Issue by LP940708** [TRI-ML/packnet-sfm#4]
docker build \
	-t packnet-sfm:master-latest . -f docker/Dockerfile
ERRO[0001] failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial unix /var/run/docker.sock: connect: permission denied 
error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=docker%2FDockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=73lzetomzynf87189u2c8lnrk&shmsize=0&t=packnet-sfm%3Amaster-latest&target=&ulimits=null&version=1: context canceled
Makefile:33: recipe for target 'docker-build' failed
make: *** [docker-build] Error 1

**Comment by madebyollin** [comment]
https://docs.docker.com/engine/install/linux-postinstall/ seems like you haven't done the docker post-install steps (this is unrelated to packnet)

**Comment by LP940708** [comment]
> https://docs.docker.com/engine/install/linux-postinstall/ seems like you haven't done the docker post-install steps (this is unrelated to packnet)

when I try "sudo bash evaluate_kitti.sh", it works, but new issue appears as following:
+ MODEL_PATH=/data/models/packnet/PackNet_MR_selfsup_K.pth.tar
+ INPUT_PATH=/data/datasets/KITTI_raw/data_splits/eigen_test_files.txt
+ DEPTH_TYPE=velodyne
+ CROP=garg
+ SAVE_OUTPUT=output
+ python scripts/evaluate_depth.py --pretrained_model /data/models/packnet/PackNet_MR_selfsup_K.pth.tar --input_path /data/datasets/KITTI_raw/data_splits/eigen_test_files.txt --depth_type velodyne --crop garg --save_output output
Traceback (most recent call last):
  File "scripts/evaluate_depth.py", line 146, in <module>
    main()
  File "scripts/evaluate_depth.py", line 47, in main
    disp_net, checkpoint_args = load_dispnet_with_args(args)
  File "/workspace/self-supervised-learning/scripts/train_sfm_utils.py", line 13, in load_dispnet_with_args
    checkpoint = torch.load(args.pretrained_model)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 382, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/data/models/packnet/PackNet_MR_selfsup_K.pth.tar'
Makefile:41: recipe for target 'docker-evaluate-depth' failed
make: *** [docker-evaluate-depth] Error 1

But  I have downloaded the model "PackNet_MR_selfsup_K.pth.tar" and put it in the correct dir. I don't know why this error happened.

**Comment by vguizilini** [comment]
Did you put your file on /data/models/packnet or data/models?

**Comment by LP940708** [comment]
> Did you put your file on /data/models/packnet or data/models?
put  the model "PackNet_MR_selfsup_K.pth.tar" on /data/models/packnet

**Comment by madebyollin** [comment]
you've put it in the wrong location (the path in the script is absolute, since it starts with a `/`). see e.g. https://web.stanford.edu/class/archive/cs/cs107/cs107.1194/resources/paths for an explanation of how to interpret file paths.

either modify the script to use relative paths like `data/models/packnet` (no leading slash) or move everything to a top-level `/data/` directory as the script expects.

**Comment by LP940708** [comment]
> you've put it in the wrong location (the path in the script is absolute, since it starts with a `/`). see e.g. https://web.stanford.edu/class/archive/cs/cs107/cs107.1194/resources/paths for an explanation of how to interpret file paths.
> 
> either modify the script to use relative paths like `data/models/packnet` (no leading slash) or move everything to a top-level `/data/` directory as the script expects.

thanks, when I modify the script to use relative paths like `data/models/packnet`,it works, but where can I find the file 'eigen_test_files.txt', and what the file contains?
+ python scripts/evaluate_depth.py --pretrained_model data/models/packnet/PackNet_MR_selfsup_K.pth.tar --input_path data/datasets/KITTI_raw/data_splits/eigen_test_files.txt --depth_type velodyne --crop garg --save_output output
DepthNet: PackNet01
Loaded disp net of type PackNet01_1A
Traceback (most recent call last):
  File "scripts/evaluate_depth.py", line 146, in <module>
    main()
  File "scripts/evaluate_depth.py", line 67, in main
    depth_type=args.depth_type)
  File "/workspace/self-supervised-learning/monodepth/datasets/kitti_context_loader.py", line 45, in __init__
    append_left_and_right_images)
  File "/workspace/self-supervised-learning/monodepth/datasets/kitti.py", line 34, in __init__
    with open(file_list, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/datasets/KITTI_raw/data_splits/eigen_test_files.txt'
Makefile:41: recipe for target 'docker-evaluate-depth' failed
make: *** [docker-evaluate-depth] Error 1

**Comment by vguizilini** [comment]
These are the split files, they contain a list of all images that will be evaluated. For KITTI they are available in many places, would it be better if we provide them here?

**Comment by LP940708** [comment]
> These are the split files, they contain a list of all images that will be evaluated. For KITTI they are available in many places, would it be better if we provide them here?

I think it wil be better if you provide them here.

**Comment by soulslicer** [comment]
How do i run this without docket? I just want to run a python file directly!

**Comment by vguizilini** [comment]
You can run it without docker if you install all dependencies on a local environment. You can check on the dockerfile what are the dependencies, soon I will add more information on that.
