### ISSUE TITLE
Issue with saving the output from the Infer.py

### ISSUE THREAD

**Issue by soheilAppear** [TRI-ML/packnet-sfm#45]
My issue is although I'm running the program correctly and it wrote that "saving ... to ..." but I cannot see the output.

I have no idea why am I getting this issue, but I assume it relates to the permission problem.

I appreciate it if someone helps me and gives me idea of how to fix it.

**Comment by VitorGuizilini-TRI** [comment]
Did you specify an output folder (the "--output" argument)? 
The folder should exist and you should have permission to write to it. Let me know if that's the case.

**Comment by soheilAppear** [comment]
Yes. I specified the directory. Also, I have A root access.  however, it does not give me any error or warning. Its normally writing the file and save it. Also, I also tried to create a file but I didn't see where it stored the file. I printed the current directory path and it showed me "workspace/packnet-sfm"

I think maybe the issue relates to the where docker stored the files.

Also, I was able to run it several times and got the output correctly. But suddenly this issue happened!

I really appreciate if you help me with this problem.

**Comment by soheilAppear** [comment]
I rerun it again and it worked this time!

I only removed sudo from the beginning of the command. I do not know how it got fixed. :| 

I entered all the commands correctly before and it wasn't working correctly.

Also, the code will automatically create directory that wants to write in it. So we don't have to necessarily create that directory manually.

**Comment by VitorGuizilini-TRI** [comment]
I'm glad it worked out for you!
