### ISSUE TITLE
Semantically-Guided Representation Learning - also during inference?

### ISSUE THREAD

**Issue by cgebbe** [TRI-ML/packnet-sfm#46]
First of all thank you for sharing your paper and code. One question concerning "Semantically-Guided Representation Learning for Self-Supervised Monocular Depth":  Is the pretrained semantic network also necessary during inference or only during training?

**Comment by VitorGuizilini-TRI** [comment]
The pretrained semantic network is also required during inference, so you need to run both and use the semantic features as input to the pixel-adaptive depth convolutions.

**Comment by cgebbe** [comment]
Thank you very much for the quick reply!

**Comment by soheilAppear** [comment]
sudo make docker-run COMMAND="python3 scripts/eval.py --checkpoint ./checkpoints/ResNet18_MR_selfsup_K.ckpt --config ./configs/eval_kitti.yaml"


This is the command I used for the evaluation part. But it did not work because of the error I mentioned at the beginning.
