### ISSUE TITLE
About memory leaks

### ISSUE THREAD

**Issue by MingYang-buaa** [TRI-ML/packnet-sfm#47]
Hi! When i'm trying to train the SelfSupModel ,I found that memory usage is growing slowly (from 21G to 38G in one epoch). That's meant memory leaks? Any solution?

**Comment by MingYang-buaa** [comment]
I may found the answer.https://github.com/TRI-ML/packnet-sfm/blob/f824ffceba46ae1c621e1bf22a35634d8b39207c/packnet_sfm/trainers/horovod_trainer.py#L90
outputs hold the output['loss'] in the all epoch that cause the memory leaks. Also after one epoch , the memory will be free.

**Comment by VitorGuizilini-TRI** [comment]
You are right, we should detach output['loss'] before appending it. 
I can push a quick PR that fixes that, or do you want to do it yourself?

**Comment by MingYang-buaa** [comment]
Thank you for your confirmation. I just to figure it out by commented out the outputs dict. That is not a suitable solution, so I’m looking forward to your PR :)
