### ISSUE TITLE
How to get the 3D LiDAR point clouds from the npz file in the Velodyne directory?

### ISSUE THREAD

**Issue by soheilAppear** [TRI-ML/packnet-sfm#48]
Hi,

I wanted to get the 3d points cloud of LiDAR points in the Velodyne directory.

However, I was not sure what software is good to convert these point cloud to a 3d point in the software that I can see the 3D view of all of these point clouds?

I appreciate it if you help me with it.
Best Regards,
Soheil.

**Comment by VitorGuizilini-TRI** [comment]
We are working on visualization for the repository, we should have something soon. In the meantime, you can use the reconstruct method of our camera class to produce 3D points from a depth map (both ground-truth and prediction), and save them to visualize externally with some other tool.

**Comment by soheilAppear** [comment]
THANKS!

**Comment by Navhkrin** [comment]
Greetings,

I can suggest this simple tool I have written on PyOpenGL for visualizing point clouds
https://github.com/Navhkrin/DepthVisualizer
