### ISSUE TITLE
PackNet Training Based on our own Dataset and Question about train_kitti.yaml 

### ISSUE THREAD

**Issue by soheilAppear** [TRI-ML/packnet-sfm#49]
Hi,

I wanted to use training part for my own dataset. However, I'm not sure what are the information do I need for the training part?
Do we need point clouds in addition to the images of our own dataset?

also in the config files in train_kitti.yaml file:

  "  params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0    "

What are params and how did you determine the min and max depth? Is it only based on the Kitti dataset or something else?

Thank you so much!
Soheil.

**Comment by soheilAppear** [comment]
e.g. is it possible also to train the model based on Tiny Kitti datasets also? If yes what part of the information is needed from the raw_kitti dataset?

**Comment by soheilAppear** [comment]
Is there any specific preparation that we should do on our own dataset in order to run the PackNet Training on our own dataset?

**Comment by VitorGuizilini-TRI** [comment]
Thank you for the interest in our work! 

- For self-supervised learning you only need to provide images, with the appropriate context (backward and forward), plus the camera intrinsics. 
- These parameters are for evaluation only, they determine which depth range and image area you consider when calculating the metrics. 
- We provide KITTI_tiny directly, you can download it and run any model, it's a quick way to see if your networks and losses are working (an overfit test).

**Comment by porwalnaman01** [comment]
Hi, is there any way to predict camera intrinsics for every image in the dataset.?
