### ISSUE TITLE
Simple overfitting test error

### ISSUE THREAD

**Issue by tonytu16** [TRI-ML/packnet-sfm#50]
![Screen Shot 2020-07-21 at 1 19 23 PM](https://user-images.githubusercontent.com/33640387/88102664-cc176c80-cb54-11ea-80ea-70ad46e3de22.png)
I am getting this ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all() error. How should I fix this? 
Thanks!

**Comment by VitorGuizilini-TRI** [comment]
Did you do any modifications to the configuration file? Which one are you using?

**Comment by tonytu16** [comment]
Hello, thank you for your reply. I used configs/overfit_kitti.yaml.

**Comment by VitorGuizilini-TRI** [comment]
Did you change the code in any way? From your error log the issue is on line 83 of augmentations.py (`if intrinsics:`), but our code does not make this check there (or anywhere). In any case, the error makes sense, because intrinsics is not a boolean, so you should be more specific when creating the `if` condition.

**Comment by tonytu16** [comment]
I see. I was able to resolve the issue and train the model. Could you let me know where the checkpoint file is saved to after training? I don't see that indicated anywhere. Thank you!

**Comment by MingYang-buaa** [comment]
@tonytu16 Hey, you may look in default_config.py and the line 22 is all you need.

**Comment by tonytu16** [comment]
<img width="1203" alt="Screen Shot 2020-07-26 at 11 30 48 AM" src="https://user-images.githubusercontent.com/33640387/88486569-76b3d480-cf33-11ea-855c-c1914016f0e8.png">

Thank you for your response! I am getting the following error after training. I am a bit confused since the self-supervised monocular depth estimation only trains on RGB data, but why is read_npz_depth returning error since depth images are not required for training? Thank you!

**Comment by VitorGuizilini-TRI** [comment]
This error is showing up during validation (see the first line of your log), where depth maps are necessary. Although I am not sure why it is failing to load the .npz depth map.

**Comment by tonytu16** [comment]
I see. so my understanding is that depth maps (npz for kitti) are not required for training but are required for validation so it must be present in the data file? What if I am training on my own custom dataset and all I have is the RGB frames? Is there a flag which I can change to train and save my model without error? Or is there a way to skip validation because I only want to see the inference results using the model I train on my custom dataset.

**Comment by VitorGuizilini-TRI** [comment]
That is a very interesting feature request, I'll add support to that soon!
