### ISSUE TITLE
Checkpoint (.ckp) produced files size

### ISSUE THREAD

**Issue by soheilAppear** [TRI-ML/packnet-sfm#55]
I have a question about the size of checkpoint files. Why they all have the same size (519.6 MB). Even I train the program with a tiny version produced checkpoint file has the same volume as you shared it. Is there any specific reason?

**Comment by VitorGuizilini-TRI** [comment]
The checkpoint size is given by the networks we use, not by dataset size. The number of weights are the same regardless of how many images we use when training them.
