### ISSUE TITLE
Question about using monocular camera images dataset

### ISSUE THREAD

**Issue by soheilAppear** [TRI-ML/packnet-sfm#56]
I was checking the Kitti dataset that you used and noticed there are Right and Left side camera images for the training process. Is it possible for us to use only one camera for the training process with PackNet? (I mean not using left and right camera images)

Thanks,
Soheil

**Comment by soheilAppear** [comment]
I mean do we need a pair of cameras for left and right images at the same time? or one camera is fine for the training process?

**Comment by VitorGuizilini-TRI** [comment]
One camera is completely fine, that is how we train all of our models. We support KITTI right and left image loading for completeness, and also because we can use them independently as data augmentation.
