### ISSUE TITLE
About producing depth map files (.npz file)

### ISSUE THREAD

**Issue by soheilAppear** [TRI-ML/packnet-sfm#59]
Is it possible for us to produce depth map files (.npz or .png) files using PackNet for our dataset? Since I noticed the KITTI dataset already provided depth map files in the separated directory. What should we do if don't have depth map files for our own dataset? Is it still trainable on our own dataset without a depth map?

Thanks.

**Comment by VitorGuizilini-TRI** [comment]
For self-supervised training you don't need depth maps at all, only for evaluation. If you don't have depth maps for evaluation then you can visually inspect the resulting predictions and see if they look alright (or you can lift them to 3D and inspect the unscaled pointclouds). You can then save these predictions as depth maps in .png or .npz using our repository.

**Comment by soheilAppear** [comment]
But the issue is if I do not use depth map files during the training process, I will not be able to run the training? So how can I prevent this issue from happening? That was the reason I thought maybe wee need a depth map even only for the training process.

**Comment by soheilAppear** [comment]
also, did you convert .bin files in KITTI dataset to .npz yourself?

My question is how can I convert them from .npz to .PNG and what are the values inside these .npz files.

I tried to open .npz files and this is the output:

0.         0.         0.         0.         0.         6.9825015
0.         6.977509   0.         0.         6.991474   0.
6.970525   0.         6.978501   0.         0.         6.984487
6.9864755  0.         6.9804935  0.         6.98248    0.
0.         6.980488   0.         6.980485   0.         0.
6.9824715  6.9705024  0.         6.9814677  0.         0.
6.977475   0.         6.9714932  0.         6.972481   0.
0.         6.9954133  0.         6.993421   6.9595056  0.
0.         6.980449   0.         6.9734573  0.         6.968465
0.         0.         6.9714513  0.         6.974438   6.977426
0.         6.9804125  0.         0.         6.971431   0.
6.9684386  0.         0.         6.9923615  0.         6.967423
0.         6.9624305  0.         6.984365   0.         6.969405
0.         6.960424   0.         0.         6.967389   0.
6.9604077  0.         6.9643836  0.         0.         6.9753485
6.95939    0.         6.959377   0.         0.         6.9723315
0.         6.9703283  0.         0.         6.960347   0.
6.969312   0.         0.         0.         6.946362   0.
0.         0.         0.         0.         0.         0.

what are these 6 columns in this .npz file? I thought maybe they are RGB and X,Y,Z coordinates. Is it right?

**Comment by VitorGuizilini-TRI** [comment]
These should be metric depth for each pixel (zeros are pixels without valid depth). What is the shape of the matrix you get when loading the .npz file?

**Comment by soheilAppear** [comment]
each matrix consists of 207 * 6 elements and the whole files have 155250 rows * 6 columns. This file is 0000000000.npz
