### ISSUE TITLE
training on huge amount of images like KITTI_raw dataset

### ISSUE THREAD

**Issue by soheilAppear** [TRI-ML/packnet-sfm#60]
I know its a very general question but I appreciate it if you tell me your opinion.

Is it possible to do the training from the scratch with one GPU (Nvidia GTX 1060 (6GB Memory)) and 16 GB RAM?

What is the ideal system specification for training process from scratch? (like how many GPUs and what model? How much memory?)

Thanks,
Soheil.

**Comment by VitorGuizilini-TRI** [comment]
It will be tough to train PackNet with this hardware, I recommend using the DepthResNet network in this case.

https://github.com/TRI-ML/packnet-sfm/blob/master/packnet_sfm/networks/depth/DepthResNet.py

**Comment by soheilAppear** [comment]
What is the minimum requirement then? How about 2 graphic cards NVIDIA GTX 1080 and 64 GB RAM? is it possible to train the network with this hardware?

**Comment by VitorGuizilini-TRI** [comment]
It should be possible, but much easier to fine-tune from a pre-trained model. Convergence from scratch takes a long time and is very sensitive, we cannot guarantee convergence to the same values every time.

**Comment by tiassap** [comment]
Sorry to ask question on closed thread. But the question I want to ask is related to this.

Is it possible to train packnet using Ubuntu 20.04LTS, NVIDIA Driver Version: 460.27.04 CUDA Version: 11.2, and GeForce RTX 3070 8 GB?

on the readme it is written that the minimum GPU requirement is 6GB..

Thank you in advance for any response!
