### ISSUE TITLE
Training on Arbitrary Videos

### ISSUE THREAD

**Issue by khaghanijavad** [TRI-ML/packnet-sfm#62]
Hi, thanks for your excellent work. I wanted to train Packnet-sfm on videos taken in the wild. To do so, at-least, I need to also estimate the camera intrinsic parameters using another network. I wanted to know whether you have tried this before, and if so, how was the performance. 

Thanks.

**Comment by VitorGuizilini-TRI** [comment]
Thank you very much! Right now we do not support training without known camera parameters  -- although we are planning to change that very soon, so stay tuned :). In the meantime, we have experimented with [this paper](https://arxiv.org/abs/1904.04998) before, it seems like what you are looking for (and not that hard to integrate with our codebase).

**Comment by khaghanijavad** [comment]
Thanks for your reply. Do you know when the new update will be released? 

Thanks for the suggestion. I have seen that paper, and I believe that integrating their camera intrinsics learning with your code can help many researchers :) If it takes a long time to release that update, I should start to integrate their method with your code. 

Thanks.

**Comment by ffabi** [comment]
I am also planning on adding trainable intrinsics to the codebase.

@VitorGuizilini-TRI Do you have any update on this topic?

@khaghanijavad Do you have any progress in the integration of this feature?

Thanks, Fabian

**Comment by khaghanijavad** [comment]
Hi @ffabi, sorry for my late response. I was busy with another project, and I have not much progress with this. 
Sincerely, Javad

**Comment by CaptainEven** [comment]
@VitorGuizilini-TRI Can this repo be used to train any videos from mono-camera with known intrinsics, or can only be trained on bino-cameras?

**Comment by porwalnaman01** [comment]
Hello there, has any one found a way to predict camera intrinsics by modifying this code bse? @CaptainEven @khaghanijavad @ffabi @VitorGuizilini-TRI
