### ISSUE TITLE
Will there be a version that adds support for pose eval？

### ISSUE THREAD

**Issue by MingYang-buaa** [TRI-ML/packnet-sfm#65]
Hi, I want to evaluate poses predicted by models for some reasons, but I found no relevant code. 
Will there be a version that adds support for pose eval？

**Comment by VitorGuizilini-TRI** [comment]
We are planning to support pose inference, but there is no ETA for that at the moment. 
In the meantime, you can have a look at this fork: https://github.com/cbaus/packnet-sfm/blob/add_pose_inference/scripts/infer_pose.py

**Comment by MingYang-buaa** [comment]
Thanks for your works. I may try to add support for ETA based on the infer_pose.py and monodepth2.
