### ISSUE TITLE
Using packnet for pseudo lidar. Packnet pointcloud showing a visible shift wrt to GT

### ISSUE THREAD

**Issue by singhg77** [TRI-ML/packnet-sfm#67]
Hi,
Thanks for contributing a great repository for monocular depth prediction.
One of the applications of monocular depth prediction is to use it as a first step to 3D object detection by generating a psuedo lidar pointcloud.
Using pretrained weights (PackNet, Self-Supervised Scale-Aware, 384x1280, CS → K) I can see that the point cloud generated for KITTI 3D object detection training set images has a small but significant right shift with respect to GT pointcloud as per the attached images. Is it explained only by the errors in monocular depth prediction in your view ? Have you run any experiments with training for object detection using the pointcloud generated using packnet ?

In images - left side is lidar BEV view, right side image is Packnet BEV view. Bounding boxes are GT bounding boxes from KITTI training set.

Best,
Gaurav
![000063](https://user-images.githubusercontent.com/5043249/89567069-f2384000-d7d5-11ea-9aaf-074006a073b8.png)
![000089](https://user-images.githubusercontent.com/5043249/89567088-f82e2100-d7d5-11ea-9cb4-3771524c82a0.png)
![000093](https://user-images.githubusercontent.com/5043249/89567146-09772d80-d7d6-11ea-94bd-c37bcf98a34c.png)
![000094](https://user-images.githubusercontent.com/5043249/89567147-0a0fc400-d7d6-11ea-9a06-896a35dbe3f1.png)
![000000](https://user-images.githubusercontent.com/5043249/89567208-23187500-d7d6-11ea-901a-3fc1a4d100a7.png)
![000108](https://user-images.githubusercontent.com/5043249/89567210-23b10b80-d7d6-11ea-98c1-df87b5af8a4a.png)
![000113](https://user-images.githubusercontent.com/5043249/89567213-2449a200-d7d6-11ea-934c-20dfe4a0488f.png)

**Comment by VitorGuizilini-TRI** [comment]
Hmm, that is very interesting. We are currently looking into using PackNet for downstream tasks, and 3D object detection is definitely a promising direction. I don't have a definite answer to you, but it looks like you are using the velocity supervised model, which never saw ground-truth depth maps at training time. So, my guess is that this shift is due to LiDAR-camera misalignments, which the depth network never learned to correct because it was never exposed to depth supervision in the first place.  Can you try with one of our semi-supervised models, to check if the shift is still there?

In any case, that's a very interesting finding, thanks for sharing that with us!

**Comment by singhg77** [comment]
Sure, will try with the semi-supervised model to check and will share!

**Comment by kwea123** [comment]
I think the shift is a common problem for all kinds of self-supervised monocular methods, that's why these methods have low score on the kitti leaderboard. If you want to use the pseudo point cloud for detection I think some sort of GT is required as mentioned by the author.

**Comment by singhg77** [comment]
Tried with the semi supervised model. The point cloud is a bit better. Left side is GT pointcloud

Images top to bottom - DORN pointcloud, Packnet semi supervised, Packnet self supervised.
![Screenshot from 2020-08-24 16-24-24](https://user-images.githubusercontent.com/5043249/91105975-6112f700-e626-11ea-8f04-b77f144d5d3e.png)
![Screenshot from 2020-08-24 16-23-40](https://user-images.githubusercontent.com/5043249/91105978-61ab8d80-e626-11ea-8c39-97f4563bd431.png)

**Comment by pravn** [comment]
This is very nice. Can you post how you generated BEV (script repo?)?
Thanks
Praveen
