### ISSUE TITLE
Training from the pretrained model

### ISSUE THREAD

**Issue by tonytu16** [TRI-ML/packnet-sfm#69]
Hello, 

I am trying to train from PackNet01_HR_velsup_CStoK.ckpt using my own dataset. 
So my training command is python train.py PackNet01_HR_velsup_CStoK.ckpt 
However I get a FileNotFoundError: [Errno 2] No such file or directory: '/data/datasets/KITTI_raw/data_splits/eigen_test_files.txt' error

It looks like the model is still expecting the KITTI dataset. Is there a way to change this? Thank you!

**Comment by VitorGuizilini-TRI** [comment]
If you provide the checkpoint like that the training will resume, will presumes that the same dataset is available. If you want to fine-tune a pre-trained model on your own dataset, you have to provide a new config (.yaml) file and include:
```
model:
    checkpoint_path: /path/to/file.ckpt
```

Let me know if that works!

**Comment by tonytu16** [comment]
Thank you! Will this overwrite the pretrained model or will the fine-tuned version of the model be saved to a new folder?

**Comment by VitorGuizilini-TRI** [comment]
It will be saved to a new folder (remember to specify the details of where the fine-tuned model will saved in the config file).
