### ISSUE TITLE
official validation split of nuScenes

### ISSUE THREAD

**Issue by jdk9405** [TRI-ML/packnet-sfm#70]
Hi, thanks for your amazing works.

I am currently evaluating the depth performance of nuScenes.
But when I got the test set of nuScenes, there are only 6008 images,
which is not 6019 images in the supplementary "Semantically-Guided Representation Learning for Self-supervised Monocular Depth"
Can you inform me which split you used?
Thank you!

**Comment by VitorGuizilini-TRI** [comment]
We used the validation split, it contains 6019 images. The test split contains 6008. I might be wrong though, could you please double check?
