### ISSUE TITLE
Updated Makefile and DockerFile for DOcker 19.03 and Cuda 11

### ISSUE THREAD

**Issue by 10Exahertz** [TRI-ML/packnet-sfm#73]
Hi, 
I installed using Cuda 11 drivers and Docker 19.02 where nvidia-docker2 is deprecated.
However I am getting this warning attempting to set-up and run with docker
```
input: make docker-run COMMAND="python3 scripts/train.py configs/overfit_kitti.yaml"

output: (last few lines)
/bin/sh: 1: nvidia-docker: not found
Makefile:77: recipe for target 'docker-run' failed
make: *** [docker-run] Error 127

```

I believe the deprecated commands are still being used, do you have updated files for the most recent versions?
Any help here would be greatly appreciated!

**Comment by VitorGuizilini-TRI** [comment]
We are currently updating to Pytorch 1.6 and Cuda 10.2, I will update the repository as soon as we reach a stable version.
