### ISSUE TITLE
Replace horovod with DDP

### ISSUE THREAD

**Issue by MingYang-buaa** [TRI-ML/packnet-sfm#75]
Hey, Is there anyone has tried to replace horovod with ddp? 
I'm trying to train the model with DDP, but i failed to replace the hvd.allreduce with torch.all_reduce.
Open to any suggestion.

**Comment by VitorGuizilini-TRI** [comment]
I'm very interested in eventually replacing horovod with ddp. Unfortunately that is not a high priority right now for the repository, but if you manage to get it working please let me know!  I will have a look as well to see if I find a way around this all_reduce issue. Thanks!
