### ISSUE TITLE
Mean and std for Dataset

### ISSUE THREAD

**Issue by MingYang-buaa** [TRI-ML/packnet-sfm#76]
Hey, where there mean and std for the KITTI datasets? I find that the DepthResNet using mean and std for image as:
`
x = (input_image - 0.45) / 0.225
`
But I cannot find  such Normalization in PackNet.

**Comment by VitorGuizilini-TRI** [comment]
Hi, we do not perform any mean/std normalization for PackNet, since it is not ImageNet pre-trained, and we did not observe any improvements in doing so relative to the standard normalization between 0 and 1.

**Comment by MingYang-buaa** [comment]
Thanks, I got it!
