### ISSUE TITLE
Deploying model for real time performance

### ISSUE THREAD

**Issue by surfii3z** [TRI-ML/packnet-sfm#79]
Hi,

I am really excited with your work and thanks for sharing with us an amazing software.

I read in the paper that you guys can archive 60 ms performance with Tesla V100 which is impressive.

However, when I tried to use "PackNet, Self-Supervised Scale-Aware, 384x1280, CS → K" with Tesla V100 in docker environment, it infers each image in ~500 ms. While "PackNet, Self-Supervised Scale-Aware, 192x640, CS → K" did better at ~ 150 ms.

I would like to know what model that you employed to get the 60 ms performance. And how could I run the inference with TensorRT as mention in the paper.

Best Regards,

Jedsadakorn

**Comment by VitorGuizilini-TRI** [comment]
I'm glad you like our repository, hopefully it will be useful for you and your research!  

The numbers we report are based on TensorRT implementations, that should be why you are observing slower inference speeds.  NVidia has a tutorial where they discuss converting PackNet using TensorRT, maybe you can find more information there:

https://docs.nvidia.com/deeplearning/tensorrt/sample-support-guide/index.html

**Comment by surfii3z** [comment]
> I'm glad you like our repository, hopefully it will be useful for you and your research!
> 
> The numbers we report are based on TensorRT implementations, that should be why you are observing slower inference speeds. NVidia has a tutorial where they discuss converting PackNet using TensorRT, maybe you can find more information there:
> 
> https://docs.nvidia.com/deeplearning/tensorrt/sample-support-guide/index.html

Thank you for your kind suggestion. I would like to try. I will update you with the result.

**Comment by surfii3z** [comment]
It turns out that the disparity (inverse of the depth) inference itself can be run with (~20 ms) on Tesla V100. But the number I reported also included the time that program download tensor from GPU to CPU to save as the depth image (~ 3x0 ms).

**Comment by surfii3z** [comment]
I came back with the more accurate inference time measurement following this [guide](https://deci.ai/the-correct-way-to-measure-inference-time-of-deep-neural-networks/).

It is ~ 235 ms with PackNet01_HR_velsup_CStoK.ckpt model.

And it is ~70 ms with PackNet01_MR_velsup_CStoK.ckpt model (The size is one-forth of the previous one)
