### ISSUE TITLE
Makefile:65: recipe for target 'docker-build' failed

### ISSUE THREAD

**Issue by 553681001atqqpointcom** [TRI-ML/packnet-sfm#80]
I do have docker being installed(according to nvidia installation guide), but when //sudo make docker-build// there is something 
 wrong just like :

...
...
...
Reading package lists...
E: Failed to fetch https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/x86_64/Packages.gz  File has unexpected size (333940 != 334425). Mirror sync in progress? [IP: 202.194.101.19 443]
   Hashes of expected file:
    - Filesize:334425 [weak]
    - SHA256:368427dc3efc0befcdbcfc3927728878cde0066efea00e53edf3f126775c8149
    - SHA1:c41f40486a99db57667aafbdf2625d9930b42067 [weak]
    - MD5Sum:39e1a1818947e57e167e4f8fd4916e0b [weak]
   Release file created at: Fri, 09 Oct 2020 01:21:10 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/bash -cu apt-get update && apt-get install -y --allow-downgrades --allow-change-held-packages --no-install-recommends     build-essential     cmake     g++-4.8     git     curl     docker.io     vim     wget     ca-certificates     libcudnn7=${CUDNN_VERSION}     libnccl2=${NCCL_VERSION}     libnccl-dev=${NCCL_VERSION}     libjpeg-dev     libpng-dev     python${PYTHON_VERSION}     python${PYTHON_VERSION}-dev     python3-tk     librdmacm1     libibverbs1     ibverbs-providers     libgtk2.0-dev     unzip     bzip2     htop     gnuplot     ffmpeg' returned a non-zero code: 100
Makefile:65: recipe for target 'docker-build' failed
make: *** [docker-build] Error 100

**Comment by tjdahlke** [comment]
I had no issues building from the Dockerfile. While this doesn't help with your problem directly, a pre-built docker image may help you circumvent the issue entirely:

For example:
[https://hub.docker.com/r/tjdahlke/packnet-sfm](https://hub.docker.com/r/tjdahlke/packnet-sfm)

Or potentially any of these:
[https://hub.docker.com/search?q=packnet-sfm&type=image](https://hub.docker.com/search?q=packnet-sfm&type=image)

**Comment by TheRustlessSummer** [comment]
Hello, I'm sorry to bother you, I met the same question with you, have you changed this question when you use the docker evn?

**Comment by zshn25** [comment]
> I do have docker being installed(according to nvidia installation guide), but when //sudo make docker-build// there is something
> wrong just like :
> 
> ...
> ...
> ...
> Reading package lists...
> E: Failed to fetch https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/x86_64/Packages.gz File has unexpected size (333940 != 334425). Mirror sync in progress? [IP: 202.194.101.19 443]
> Hashes of expected file:
> - Filesize:334425 [weak]
> - SHA256:368427dc3efc0befcdbcfc3927728878cde0066efea00e53edf3f126775c8149
> - SHA1:c41f40486a99db57667aafbdf2625d9930b42067 [weak]
> - MD5Sum:39e1a1818947e57e167e4f8fd4916e0b [weak]
> Release file created at: Fri, 09 Oct 2020 01:21:10 +0000
> E: Some index files failed to download. They have been ignored, or old ones used instead.
> The command '/bin/bash -cu apt-get update && apt-get install -y --allow-downgrades --allow-change-held-packages --no-install-recommends build-essential cmake g++-4.8 git curl docker.io vim wget ca-certificates libcudnn7=${CUDNN_VERSION} libnccl2=${NCCL_VERSION} libnccl-dev=${NCCL_VERSION} libjpeg-dev libpng-dev python${PYTHON_VERSION} python${PYTHON_VERSION}-dev python3-tk librdmacm1 libibverbs1 ibverbs-providers libgtk2.0-dev unzip bzip2 htop gnuplot ffmpeg' returned a non-zero code: 100
> Makefile:65: recipe for target 'docker-build' failed
> make: *** [docker-build] Error 100

Same error even with [pre-built docker image](https://hub.docker.com/r/tjdahlke/packnet-sfm)

**Comment by llk2why** [comment]
@zshn25 Have you solved this problem?  I met the same situation, both building from Docker file and pulling down pre-built image
