### ISSUE TITLE
failed at "make docker-build"

### ISSUE THREAD

**Issue by TheRustlessSummer** [TRI-ML/packnet-sfm#81]
![image](https://user-images.githubusercontent.com/48950800/96007071-baeaad00-0e70-11eb-844e-aac242f9a9c4.png)
![image](https://user-images.githubusercontent.com/48950800/96007323-f5ece080-0e70-11eb-8d89-7f0b2cb1f633.png)

Hello, when I run `make docker-build` , the question shows in the figure.

**Comment by tjdahlke** [comment]
This doesn't help with your problem directly, but a pre-built docker image may help you circumvent the issue entirely:

For example:
[https://hub.docker.com/r/tjdahlke/packnet-sfm](https://hub.docker.com/r/tjdahlke/packnet-sfm)

Or potentially any of these:
[https://hub.docker.com/search?q=packnet-sfm&type=image](https://hub.docker.com/search?q=packnet-sfm&type=image)

**Comment by TheRustlessSummer** [comment]
> This doesn't help with your problem directly, a pre-built docker image may help you circumvent the issue entirely:
> 
> For example:
> https://hub.docker.com/r/tjdahlke/packnet-sfm
> 
> Or potentially any of these:
> https://hub.docker.com/search?q=packnet-sfm&type=image

hello, thanks for attention. But there are still some question after I download the docker from hdjang.
![图片](https://user-images.githubusercontent.com/48950800/97082825-0eae8080-163f-11eb-868c-37a6d1b59854.png)

**Comment by TheRustlessSummer** [comment]
> This doesn't help with your problem directly, a pre-built docker image may help you circumvent the issue entirely:
> 
> For example:
> https://hub.docker.com/r/tjdahlke/packnet-sfm
> 
> Or potentially any of these:
> https://hub.docker.com/search?q=packnet-sfm&type=image

When I saw the output of the commend "make docker-build", I have a question. I have download the docker of packenet-sfm, why I need to download other package?

**Comment by TheRustlessSummer** [comment]
> This doesn't help with your problem directly, a pre-built docker image may help you circumvent the issue entirely:
> 
> For example:
> https://hub.docker.com/r/tjdahlke/packnet-sfm
> 
> Or potentially any of these:
> https://hub.docker.com/search?q=packnet-sfm&type=image

or it failed cause the ip

> This doesn't help with your problem directly, a pre-built docker image may help you circumvent the issue entirely:
> 
> For example:
> https://hub.docker.com/r/tjdahlke/packnet-sfm
> 
> Or potentially any of these:
> https://hub.docker.com/search?q=packnet-sfm&type=image

The question always happened at step 15, maybe I think it caused by the ip

**Comment by TheRustlessSummer** [comment]
Hello, I downloaded the docker from hdjang and tjdahlke, but when I run the commend 'make docker-start-interactive', the same question still happened.



At 2020-10-24 05:24:15, "Taylor Dahlke" <notifications@github.com> wrote:

This doesn't help with your problem directly, but a pre-built docker image may help you circumvent the issue entirely:

For example:
https://hub.docker.com/r/tjdahlke/packnet-sfm

Or potentially any of these:
https://hub.docker.com/search?q=packnet-sfm&type=image

**Comment by tjdahlke** [comment]
If you are using a prebuilt docker image, you shouldn't be using the 

`make docker-build`

command, since you are trying to enter an existing docker image, _not_ build a new one. 

You want to run something along the lines of 

`docker run -it hdjang/packnet-sfm:latest`

Try using/modifying the 

`make docker-start-interactive'

command, which makes use of a similar docker command.

**Comment by TheRustlessSummer** [comment]
The commend I use was
`make docker-start-interactive`.
But the question still happened.
Or I tried to run commend
`make docker-run COMMAND="python3 scripts/train.py configs/overfit_kitti.yaml"`.
The output of these two commends were the same with
`make docker-build`.
I don't know how to do with this.



At 2020-10-26 09:20:07, "Taylor Dahlke" <notifications@github.com> wrote:

If you are using a prebuilt docker image, you shouldn't be using the

make docker-build

command, since you are trying to enter an existing docker image, not build a new one.

You want to run something along the lines of

docker run -it hdjang/packnet-sfm:latest

Try using/modifying the

`make docker-start-interactive'

command, which makes use of a similar docker command.

**Comment by tjdahlke** [comment]
Not sure what the fix is here. I wonder if you have some network settings that are not allowing the docker container to communicate properly with the `nvidia` server?

**Comment by TheRustlessSummer** [comment]
Hello,
   

    I have successfully run docker. Need I save docker before close the terminal? Or I need to redownload these package?



















At 2020-10-27 01:01:25, "Taylor Dahlke" <notifications@github.com> wrote:

Not sure what the fix is here. I wonder if you have some network settings that are not allowing the docker container to communicate properly with the nvidia server?

**Comment by tjdahlke** [comment]
No. The docker image should remain as-is on your local system unless you manually remove it.

**Comment by tjdahlke** [comment]
If this issue is now resolved for you, please consider closing it.

**Comment by TheRustlessSummer** [comment]
Thanks for your help.
