### ISSUE TITLE
Where to pass in the instantaneous velocity measurements for scale-aware depth learning?

### ISSUE THREAD

**Issue by souravagarwal** [TRI-ML/packnet-sfm#82]
-

**Comment by VitorGuizilini-TRI** [comment]
Hi, did you solve the issue?

**Comment by souravagarwal** [comment]
HI Yeah i was able to solve this issue, I got where i was missing the problem.

I have another question though - if you could help me with it (or i can open another issue and close this).

For the velocity Supervision Loss for scale-aware estimation, I could not understand how can we pass in the instantaneous velocity measurements in the yaml file (i looked at train_kitti.yaml) and could not find it.

Thanks for the quick response though!.

**Comment by VitorGuizilini-TRI** [comment]
For velocity training the instantaneous measurements are provided by the data loader, for each sample. In the config file you can define the weight for the velocity loss relative to the self supervised loss, by setting the 'velocity_loss_weight' parameter.
