### ISSUE TITLE
What do depth/depth_pp/depth_gt/depth_pp_gt mean?

### ISSUE THREAD

**Issue by hdjang** [TRI-ML/packnet-sfm#85]
Hi, 
I have a question reagarding terms used during evaluation

What do depth/depth_pp/depth_gt/depth_pp_gt mean?

Thanks.

**Comment by VitorGuizilini-TRI** [comment]
`pp` means post-processing, where we run the same image twice through the depth network (once flipped) and combine the outputs, leading to slightly better results. 
`gt` means ground-truth median-scaling at test-time, to create scale-aware predictions.

**Comment by hdjang** [comment]
It is very clear now. Thanks for your reply :)
