### ISSUE TITLE
tar: /data/datasets: Cannot open: No such file or directory

### ISSUE THREAD

**Issue by TheRustlessSummer** [TRI-ML/packnet-sfm#88]
Hello, thanks for your amazing  code, but there is a question when I run commend
`curl -s https://tri-ml-public.s3.amazonaws.com/github/DDAD/datasets/DDAD.tar | tar -xv -C /data/datasets/`
![图片](https://user-images.githubusercontent.com/48950800/97252508-12abef80-1845-11eb-81c4-49753d5b76a5.png)
But I have already done the commend `mkdir /data/datasets/`, the folder is showed below.
![图片](https://user-images.githubusercontent.com/48950800/97252577-4850d880-1845-11eb-9ff0-c0525b471ad9.png)
Just as the picture shows, I downloaded KITTI but when I ran the commend
` python3 scripts/train.py configs/overfit_kitti.yaml`
the question still happened as below
![图片](https://user-images.githubusercontent.com/48950800/97252725-a087da80-1845-11eb-946a-9dae664d59e0.png)

**Comment by TheRustlessSummer** [comment]
root@sun-MS-7A38:/workspace/packnet-sfm# python3 scripts/train.py configs/overfit_kitti.yaml
### Preparing Model
Model: SelfSupModel
DepthNet: DepthResNet
PoseNet: PoseResNet
### Preparing Datasets
###### Setup train datasets
Traceback (most recent call last):
  File "scripts/train.py", line 64, in <module>
    train(args.file)
  File "scripts/train.py", line 53, in train
    model_wrapper = ModelWrapper(config, resume=ckpt, logger=logger)
  File "/workspace/packnet-sfm/packnet_sfm/models/model_wrapper.py", line 64, in __init__
    self.prepare_datasets(validation_requirements, test_requirements)
  File "/workspace/packnet-sfm/packnet_sfm/models/model_wrapper.py", line 91, in prepare_datasets
    self.model.train_requirements, **augmentation)
  File "/workspace/packnet-sfm/packnet_sfm/models/model_wrapper.py", line 521, in setup_dataset
    **dataset_args, **dataset_args_i,
  File "/workspace/packnet-sfm/packnet_sfm/datasets/kitti_dataset.py", line 106, in __init__
    with open(file_list, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/datasets/KITTI_tiny/kitti_tiny.txt'

**Comment by VitorGuizilini-TRI** [comment]
I think you are creating `data/datasets` in the `packnet-sfm` root folder (`packnet-sfm/data/datasets`), it's supposed to be at the root of your system (`/data/datasets`), so the datasets don't get copied with the docker build. But it should work, if you change the paths accordingly (i.e. from `/data/datasets` to `data/datasets`)

**Comment by TheRustlessSummer** [comment]
> I think you are creating `data/datasets` in the `packnet-sfm` root folder (`packnet-sfm/data/datasets`), it's supposed to be at the root of your system (`/data/datasets`), so the datasets don't get copied with the docker build. But it should work, if you change the paths accordingly (i.e. from `/data/datasets` to `data/datasets`)

Thanks for your help. I have another question. How to see the results of depth map and pointcloud？

**Comment by VitorGuizilini-TRI** [comment]
When running the `eval.py` script you can choose some `save` parameters in the .yaml config file. These will save the depth maps, then you can project them to 3D using the camera intrinsics to plot using your favorite visualizer. I am working on porting my own custom visualizer to this repository, but I'm not sure when it is going to land, probably more towards the end of the year.

**Comment by TheRustlessSummer** [comment]
Thanks for your suggestion. I have another question, the dataset DADD and KITTI you used is too large for me. Can you suggest some other datasets which is smaller than 50g to be training?

**Comment by VitorGuizilini-TRI** [comment]
As a starting point you can use our `_tiny` datasets, they are good enough for overfitting and to quickly try new ideas.

**Comment by chaotianjiao** [comment]
@TheRustlessSummer Hi~, Can you tell me how to change `/data/datasets` to `data/datasets`?  Which .py should I modify? Great thanks~

**Comment by VitorGuizilini-TRI** [comment]
You can change the .yaml files directly.
