### ISSUE TITLE
How to set the learning rates when fine-tuning on KITTI with the semantic network in ICLR'20 paper

### ISSUE THREAD

**Issue by Rodger-Huang** [TRI-ML/packnet-sfm#89]
Thank you for your great work. 
I want to know how you set the learning rates when you fine-tuned the depth and pose network on KITTI in the ICLR'20 paper  _Semantically-Guided Representation Learning for Self-Supervised Monocular Depth_.
Did you set the initial depth and pose learning rates to be 2\*10-4 and 5\*10-4 or 5\*10-5 and 1.25\*10-4 in the fine-tuning stage?
I try to add a semantic segmentation network to help depth estimation and I can't see the improvement. So I want to know how you set the learning rates.

**Comment by VitorGuizilini-TRI** [comment]
How did you add the semantic network? Our ICLR paper does not do multi-tasking, it uses the semantic features to guide the generation of depth features, using Pixel-Adaptive Convolutions. Is that what you are doing?

**Comment by Rodger-Huang** [comment]
Sorry for the late reply!
Yes, I used the semantic features from the pretrained semantic network to guide the generation of depth features. I used the method of pixel-adaptive convolutions, but I didn't get great improvement like yours. Maybe I did something wrong.
By the way, you said 88250 images from CityScapes were used to pretrain the network. But as I know, there are usually 5000 images with fine annotations and around 20000 images with coarse annotations.
What packages in the CityScapes website contain the 88250 images you used?
Thanks!

**Comment by VitorGuizilini-TRI** [comment]
Are you using this repository to train your models? What about the network, is it PackNet or ResNet? Usually if you start from a pre-trained model and fine-tune using the semantically-guided extension it should work. I will double check the learning rates and other parameters (and the semantic network details, and the Cityscapes split) in the paper and come back to you.

**Comment by Rodger-Huang** [comment]
Thanks for your quick reply!
I am using the Packnet as the depth network. I am not sure that every detail of mine is the same as described in your paper. I look forward to your releasing the code so that I can learn more about the details.

**Comment by VitorGuizilini-TRI** [comment]
Hi, about the 88250 images: there is a typo, it should actually be 89250. These are the 2975 training images with the corresponding 30 unlabeled frames for each sequence, so 2975 x 30 = 89250.
