### ISSUE TITLE
about training script

### ISSUE THREAD

**Issue by KeyaoLi10** [TRI-ML/packnet-sfm#9]
I wonder why training script is not provided like other related projects

**Comment by vguizilini** [comment]
We are working on this, please check back soon!

**Comment by patrick-llgc** [comment]
Thanks for the update. @vitorguizilini 

Looking forward to the training code for `Semantically-Guided Representation Learning for Self-Supervised Monocular Depth (ICLR 2020)`!

**Comment by jinfagang** [comment]
@vguizilini When will training code provided?

**Comment by VitorGuizilini-TRI** [comment]
Our training code is now available!

**Comment by Jerrypiglet** [comment]
> Our training code is now available!

Hey Victor, thanks for the efforts of releasing the code! I am looking for the model and the training code for the ICLR'20 paper _Semantically-Guided Representation Learning for Self-Supervised Monocular Depth_, especially the **semantic guidance** module. I wonder where can I find it? Thanks!

**Comment by SBaokun** [comment]
Hello, has your problem been solved?Can you share me with  **semantic guidance module**?thanks!!!
