### ISSUE TITLE
How to run my own  dataset?

### ISSUE THREAD

**Issue by TheRustlessSummer** [TRI-ML/packnet-sfm#90]
Hello, I read your article "Neural Ray Surfaces for Self-Supervised Learning of Depth and Ego-motion", and I have a question  that how to run the code to get the results in your article of Underwater Caves dataset? And I have some under-water-videos, I want to get depth maps and point clouds. How can I do it?

**Comment by VitorGuizilini-TRI** [comment]
Hi, we are working on porting the code and pretrained models from that paper into this repository, it shouldn't be long before you can run NRS on your datasets!

**Comment by Hommus** [comment]
@VitorGuizilini-TRI Can you provide any indication of how long this dataset (caves) took to train on your 8xV100 setup?
