### ISSUE TITLE
Are there any neural ray surfaces related parts in this source?

### ISSUE THREAD

**Issue by fogfog2** [TRI-ML/packnet-sfm#97]
I have read your 'Neural Ray Surfaces for Self-Supervised Learning of Depth and Ego-motion' paper well.

This link is referenced in the paper, but I can't find the relevant part.

Are there any plans to be updated?

Thanks

**Comment by VitorGuizilini-TRI** [comment]
Hi, thank you for the interest! 
We are going to release code for NRS very soon, probably in the upcoming week or two, I will keep you informed.

**Comment by VitorGuizilini-TRI** [comment]
We have just released NRS training code, hopefully that's enough for you to replicate our results and build on top of it.
