### ISSUE TITLE
License

### ISSUE THREAD

**Issue by e2r-htz** [TRI-ML/packnet-sfm#98]
The [ResNet model](https://github.com/TRI-ML/packnet-sfm/blob/master/packnet_sfm/networks/layers/resnet/resnet_encoder.py) seems to be adapted from monodepth2, which has a different license than MIT License. Could you clarify this inconsistency please?

**Comment by VitorGuizilini-TRI** [comment]
You are right, those models should follow the monodepth2 license. I will update the files to reflect that.
